<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 15 연관규칙 | 데이터마이닝 with R</title>
  <meta name="description" content="전치혁 교수님의 책 을 기반으로 한 R 예제" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 15 연관규칙 | 데이터마이닝 with R" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://youngroklee-ml.github.io/data-mining-book/" />
  
  <meta property="og:description" content="전치혁 교수님의 책 을 기반으로 한 R 예제" />
  <meta name="github-repo" content="youngroklee-ml/data-mining-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 15 연관규칙 | 데이터마이닝 with R" />
  
  <meta name="twitter:description" content="전치혁 교수님의 책 을 기반으로 한 R 예제" />
  

<meta name="author" content="전치혁, 이혜선, 이종석, 이영록" />


<meta name="date" content="2020-12-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="cluster-solution-evaluation.html"/>
<link rel="next" href="recommender-system.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">데이터마이닝 with R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>개요</a></li>
<li class="chapter" data-level="1" data-path="datamining-overview.html"><a href="datamining-overview.html"><i class="fa fa-check"></i><b>1</b> 데이터마이닝 개요</a></li>
<li class="part"><span><b>I 1부 - 예측</b></span></li>
<li class="chapter" data-level="2" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>2</b> 회귀분석</a><ul>
<li class="chapter" data-level="2.1" data-path="regression.html"><a href="regression.html#regression-packages-install"><i class="fa fa-check"></i><b>2.1</b> 필요 R 패키지 설치</a></li>
<li class="chapter" data-level="2.2" data-path="regression.html"><a href="regression.html#multiple-linear-regression"><i class="fa fa-check"></i><b>2.2</b> 다중회귀모형</a></li>
<li class="chapter" data-level="2.3" data-path="regression.html"><a href="regression.html#regression-response-confidence-prediction"><i class="fa fa-check"></i><b>2.3</b> 반응치에 대한 추정 및 예측</a><ul>
<li class="chapter" data-level="2.3.1" data-path="regression.html"><a href="regression.html#regression-response-confidence"><i class="fa fa-check"></i><b>2.3.1</b> 평균반응치의 추정</a></li>
<li class="chapter" data-level="2.3.2" data-path="regression.html"><a href="regression.html#regression-response-prediction"><i class="fa fa-check"></i><b>2.3.2</b> 미래반응치의 예측</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="regression.html"><a href="regression.html#regression-indicator-variable"><i class="fa fa-check"></i><b>2.4</b> 지시변수와 회귀모형</a><ul>
<li class="chapter" data-level="2.4.1" data-path="regression.html"><a href="regression.html#regression-indicator-variable-basic-script"><i class="fa fa-check"></i><b>2.4.1</b> 기본 R 스트립트</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="pca.html"><a href="pca.html"><i class="fa fa-check"></i><b>3</b> 주성분분석</a><ul>
<li class="chapter" data-level="3.1" data-path="pca.html"><a href="pca.html#pca-packages-install"><i class="fa fa-check"></i><b>3.1</b> 필요 R 패키지 설치</a></li>
<li class="chapter" data-level="3.2" data-path="pca.html"><a href="pca.html#pca-matrix-factorization"><i class="fa fa-check"></i><b>3.2</b> 행렬의 분해</a><ul>
<li class="chapter" data-level="3.2.1" data-path="pca.html"><a href="pca.html#pca-matrix-factorization-basic-script"><i class="fa fa-check"></i><b>3.2.1</b> 기본 R 스트립트</a></li>
<li class="chapter" data-level="3.2.2" data-path="pca.html"><a href="pca.html#pca-ss"><i class="fa fa-check"></i><b>3.2.2</b> 변수의 변동과 제곱합</a></li>
<li class="chapter" data-level="3.2.3" data-path="pca.html"><a href="pca.html#pca-intro"><i class="fa fa-check"></i><b>3.2.3</b> 주성분의 이해 및 행렬의 분해</a></li>
<li class="chapter" data-level="3.2.4" data-path="pca.html"><a href="pca.html#pca-svd"><i class="fa fa-check"></i><b>3.2.4</b> 특이치분해 (Singular Value Decomposition)</a></li>
<li class="chapter" data-level="3.2.5" data-path="pca.html"><a href="pca.html#pca-spectral"><i class="fa fa-check"></i><b>3.2.5</b> 분광분해 (Spectral Decomposition)</a></li>
<li class="chapter" data-level="3.2.6" data-path="pca.html"><a href="pca.html#pca-nipals"><i class="fa fa-check"></i><b>3.2.6</b> NIPALS 알고리즘</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="pca.html"><a href="pca.html#pca-regression"><i class="fa fa-check"></i><b>3.3</b> 주성분 회귀분석</a><ul>
<li class="chapter" data-level="3.3.1" data-path="pca.html"><a href="pca.html#pcr-basic-script"><i class="fa fa-check"></i><b>3.3.1</b> 기본 R 스트립트</a></li>
<li class="chapter" data-level="3.3.2" data-path="pca.html"><a href="pca.html#pcr-regression-coefficient"><i class="fa fa-check"></i><b>3.3.2</b> 주성분 회귀계수 추정</a></li>
<li class="chapter" data-level="3.3.3" data-path="pca.html"><a href="pca.html#pcr-regression-transform"><i class="fa fa-check"></i><b>3.3.3</b> 회귀계수 선형변환</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="plsr.html"><a href="plsr.html"><i class="fa fa-check"></i><b>4</b> 부분최소자승법</a><ul>
<li class="chapter" data-level="4.1" data-path="plsr.html"><a href="plsr.html#plsr-packages-install"><i class="fa fa-check"></i><b>4.1</b> 필요 R 패키지 설치</a></li>
<li class="chapter" data-level="4.2" data-path="plsr.html"><a href="plsr.html#plsr-single-target"><i class="fa fa-check"></i><b>4.2</b> 하나의 종속변수의 경우</a><ul>
<li class="chapter" data-level="4.2.1" data-path="plsr.html"><a href="plsr.html#plsr-basic-script"><i class="fa fa-check"></i><b>4.2.1</b> 기본 R 스크립트</a></li>
<li class="chapter" data-level="4.2.2" data-path="plsr.html"><a href="plsr.html#plsr-model"><i class="fa fa-check"></i><b>4.2.2</b> PLS 모형</a></li>
<li class="chapter" data-level="4.2.3" data-path="plsr.html"><a href="plsr.html#plsr-single-nipals"><i class="fa fa-check"></i><b>4.2.3</b> NIPALS 알고리즘</a></li>
<li class="chapter" data-level="4.2.4" data-path="plsr.html"><a href="plsr.html#plsr-single-transform"><i class="fa fa-check"></i><b>4.2.4</b> 회귀식 변환</a></li>
<li class="chapter" data-level="4.2.5" data-path="plsr.html"><a href="plsr.html#plsr-sst"><i class="fa fa-check"></i><b>4.2.5</b> 제곱합 분해</a></li>
<li class="chapter" data-level="4.2.6" data-path="plsr.html"><a href="plsr.html#plsr-variable-importance"><i class="fa fa-check"></i><b>4.2.6</b> 독립변수의 중요도</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="plsr.html"><a href="plsr.html#plsr-multivariate-target"><i class="fa fa-check"></i><b>4.3</b> 다수의 종속변수의 경우</a><ul>
<li class="chapter" data-level="4.3.1" data-path="plsr.html"><a href="plsr.html#plsr-multivariate-basic-script"><i class="fa fa-check"></i><b>4.3.1</b> 기본 R 스크립트</a></li>
<li class="chapter" data-level="4.3.2" data-path="plsr.html"><a href="plsr.html#plsr-multivariate-model"><i class="fa fa-check"></i><b>4.3.2</b> PLS 모형</a></li>
<li class="chapter" data-level="4.3.3" data-path="plsr.html"><a href="plsr.html#plsr-multivariate-nipals"><i class="fa fa-check"></i><b>4.3.3</b> NIPALS 알고리즘</a></li>
<li class="chapter" data-level="4.3.4" data-path="plsr.html"><a href="plsr.html#plsr-multivariate-transform"><i class="fa fa-check"></i><b>4.3.4</b> 회귀식 변환</a></li>
<li class="chapter" data-level="4.3.5" data-path="plsr.html"><a href="plsr.html#plsr-multivariate-sst"><i class="fa fa-check"></i><b>4.3.5</b> 제곱합 분해</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II 2부 - 분류분석</b></span></li>
<li class="chapter" data-level="5" data-path="classification-analysis.html"><a href="classification-analysis.html"><i class="fa fa-check"></i><b>5</b> 분류분석 개요</a><ul>
<li class="chapter" data-level="5.1" data-path="classification-analysis.html"><a href="classification-analysis.html#classification-packages-install"><i class="fa fa-check"></i><b>5.1</b> 필요 R 패키지 설치</a></li>
<li class="chapter" data-level="5.2" data-path="classification-analysis.html"><a href="classification-analysis.html#classification-problem-methods"><i class="fa fa-check"></i><b>5.2</b> 분류문제 및 분류기법</a></li>
<li class="chapter" data-level="5.3" data-path="classification-analysis.html"><a href="classification-analysis.html#simple-classification-methods"><i class="fa fa-check"></i><b>5.3</b> 기본적인 분류기법</a><ul>
<li class="chapter" data-level="5.3.1" data-path="classification-analysis.html"><a href="classification-analysis.html#nearest-neighbor-classification"><i class="fa fa-check"></i><b>5.3.1</b> 인접객체법</a></li>
<li class="chapter" data-level="5.3.2" data-path="classification-analysis.html"><a href="classification-analysis.html#naive-bayes"><i class="fa fa-check"></i><b>5.3.2</b> 나이브 베이지안 분류법</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>6</b> 로지스틱 회귀분석</a><ul>
<li class="chapter" data-level="6.1" data-path="logistic-regression.html"><a href="logistic-regression.html#logistic-packages-install"><i class="fa fa-check"></i><b>6.1</b> 필요 R 패키지 설치</a></li>
<li class="chapter" data-level="6.2" data-path="logistic-regression.html"><a href="logistic-regression.html#binary-logistic-regression"><i class="fa fa-check"></i><b>6.2</b> 이분 로지스틱 회귀모형</a><ul>
<li class="chapter" data-level="6.2.1" data-path="logistic-regression.html"><a href="logistic-regression.html#bianry-logistic-reg-basic-script"><i class="fa fa-check"></i><b>6.2.1</b> 기본 R 스크립트</a></li>
<li class="chapter" data-level="6.2.2" data-path="logistic-regression.html"><a href="logistic-regression.html#binary-logistic-reg-model"><i class="fa fa-check"></i><b>6.2.2</b> 회귀모형</a></li>
<li class="chapter" data-level="6.2.3" data-path="logistic-regression.html"><a href="logistic-regression.html#binary-logistic-reg-estimation"><i class="fa fa-check"></i><b>6.2.3</b> 회귀계수 추정</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="logistic-regression.html"><a href="logistic-regression.html#nominal-logistic-regression"><i class="fa fa-check"></i><b>6.3</b> 명목 로지스틱 회귀모형</a><ul>
<li class="chapter" data-level="6.3.1" data-path="logistic-regression.html"><a href="logistic-regression.html#nominal-logistic-reg-basic-script"><i class="fa fa-check"></i><b>6.3.1</b> 기본 R 스크립트</a></li>
<li class="chapter" data-level="6.3.2" data-path="logistic-regression.html"><a href="logistic-regression.html#baseline-category-logit-model"><i class="fa fa-check"></i><b>6.3.2</b> 기준범주 로짓모형</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="logistic-regression.html"><a href="logistic-regression.html#ordinal-logistic-regression"><i class="fa fa-check"></i><b>6.4</b> 서열 로지스틱 회귀모형</a><ul>
<li class="chapter" data-level="6.4.1" data-path="logistic-regression.html"><a href="logistic-regression.html#ordinal-logistic-basic-script"><i class="fa fa-check"></i><b>6.4.1</b> 기본 R 스크립트</a></li>
<li class="chapter" data-level="6.4.2" data-path="logistic-regression.html"><a href="logistic-regression.html#cumulative-logit-model"><i class="fa fa-check"></i><b>6.4.2</b> 누적 로짓모형</a></li>
<li class="chapter" data-level="6.4.3" data-path="logistic-regression.html"><a href="logistic-regression.html#adjacent-categories-logit-model"><i class="fa fa-check"></i><b>6.4.3</b> 인근범주 로짓모형</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="da.html"><a href="da.html"><i class="fa fa-check"></i><b>7</b> 판별분석</a><ul>
<li class="chapter" data-level="7.1" data-path="da.html"><a href="da.html#da-overview"><i class="fa fa-check"></i><b>7.1</b> 개요</a></li>
<li class="chapter" data-level="7.2" data-path="da.html"><a href="da.html#da-packages-install"><i class="fa fa-check"></i><b>7.2</b> 필요 R 패키지 설치</a></li>
<li class="chapter" data-level="7.3" data-path="da.html"><a href="da.html#da-fisher"><i class="fa fa-check"></i><b>7.3</b> 피셔 방법</a><ul>
<li class="chapter" data-level="7.3.1" data-path="da.html"><a href="da.html#da-fisher-basic-script"><i class="fa fa-check"></i><b>7.3.1</b> 기본 R 스크립트</a></li>
<li class="chapter" data-level="7.3.2" data-path="da.html"><a href="da.html#피셔-판별함수"><i class="fa fa-check"></i><b>7.3.2</b> 피셔 판별함수</a></li>
<li class="chapter" data-level="7.3.3" data-path="da.html"><a href="da.html#분류-규칙"><i class="fa fa-check"></i><b>7.3.3</b> 분류 규칙</a></li>
<li class="chapter" data-level="7.3.4" data-path="da.html"><a href="da.html#r-패키지를-이용한-분류규칙-도출"><i class="fa fa-check"></i><b>7.3.4</b> R 패키지를 이용한 분류규칙 도출</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="da.html"><a href="da.html#lda"><i class="fa fa-check"></i><b>7.4</b> 의사결정론에 의한 선형분류규칙</a><ul>
<li class="chapter" data-level="7.4.1" data-path="da.html"><a href="da.html#lda-basic-script"><i class="fa fa-check"></i><b>7.4.1</b> 기본 R 스크립트</a></li>
<li class="chapter" data-level="7.4.2" data-path="da.html"><a href="da.html#lda-function"><i class="fa fa-check"></i><b>7.4.2</b> 선형판별함수</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="da.html"><a href="da.html#lda-misclassification-cost"><i class="fa fa-check"></i><b>7.5</b> 오분류비용을 고려한 분류규칙</a></li>
<li class="chapter" data-level="7.6" data-path="da.html"><a href="da.html#qda"><i class="fa fa-check"></i><b>7.6</b> 이차판별분석</a><ul>
<li class="chapter" data-level="7.6.1" data-path="da.html"><a href="da.html#qda-basic-script"><i class="fa fa-check"></i><b>7.6.1</b> 기본 R 스크립트</a></li>
<li class="chapter" data-level="7.6.2" data-path="da.html"><a href="da.html#qda-function"><i class="fa fa-check"></i><b>7.6.2</b> 이차 판별함수</a></li>
<li class="chapter" data-level="7.6.3" data-path="da.html"><a href="da.html#qda-discriminant-rule"><i class="fa fa-check"></i><b>7.6.3</b> 이차판별함수에 의한 분류</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="da.html"><a href="da.html#da-multiclass"><i class="fa fa-check"></i><b>7.7</b> 세 범주 이상의 분류</a><ul>
<li class="chapter" data-level="7.7.1" data-path="da.html"><a href="da.html#mutliclass-da-basic-script"><i class="fa fa-check"></i><b>7.7.1</b> 기본 R 스크립트</a></li>
<li class="chapter" data-level="7.7.2" data-path="da.html"><a href="da.html#mutliclass-generalized-discriminant-function"><i class="fa fa-check"></i><b>7.7.2</b> 일반화된 판별함수</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="tree-based-method.html"><a href="tree-based-method.html"><i class="fa fa-check"></i><b>8</b> 트리기반 기법</a><ul>
<li class="chapter" data-level="8.1" data-path="tree-based-method.html"><a href="tree-based-method.html#cart-overview"><i class="fa fa-check"></i><b>8.1</b> CART 개요</a></li>
<li class="chapter" data-level="8.2" data-path="tree-based-method.html"><a href="tree-based-method.html#cart-packages-install"><i class="fa fa-check"></i><b>8.2</b> 필요 R package 설치</a></li>
<li class="chapter" data-level="8.3" data-path="tree-based-method.html"><a href="tree-based-method.html#cart-build"><i class="fa fa-check"></i><b>8.3</b> CART 트리 생성</a><ul>
<li class="chapter" data-level="8.3.1" data-path="tree-based-method.html"><a href="tree-based-method.html#cart-basic-r-script"><i class="fa fa-check"></i><b>8.3.1</b> 기본 R 스크립트</a></li>
<li class="chapter" data-level="8.3.2" data-path="tree-based-method.html"><a href="tree-based-method.html#cart-notation"><i class="fa fa-check"></i><b>8.3.2</b> 기호 정의</a></li>
<li class="chapter" data-level="8.3.3" data-path="tree-based-method.html"><a href="tree-based-method.html#cart-impurity"><i class="fa fa-check"></i><b>8.3.3</b> 노드 및 트리의 불순도</a></li>
<li class="chapter" data-level="8.3.4" data-path="tree-based-method.html"><a href="tree-based-method.html#cart-split"><i class="fa fa-check"></i><b>8.3.4</b> 분지기준</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="tree-based-method.html"><a href="tree-based-method.html#cart-pruning-complete"><i class="fa fa-check"></i><b>8.4</b> 가지치기 및 최종 트리 선정</a><ul>
<li class="chapter" data-level="8.4.1" data-path="tree-based-method.html"><a href="tree-based-method.html#cart-pruning"><i class="fa fa-check"></i><b>8.4.1</b> 가지치기</a></li>
<li class="chapter" data-level="8.4.2" data-path="tree-based-method.html"><a href="tree-based-method.html#cart-best-tree"><i class="fa fa-check"></i><b>8.4.2</b> 최적 트리의 선정</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="tree-based-method.html"><a href="tree-based-method.html#cart-r-pkg"><i class="fa fa-check"></i><b>8.5</b> R패키지 내 분류 트리 방법</a><ul>
<li class="chapter" data-level="8.5.1" data-path="tree-based-method.html"><a href="tree-based-method.html#cart-r-pkg-split"><i class="fa fa-check"></i><b>8.5.1</b> 트리 확장</a></li>
<li class="chapter" data-level="8.5.2" data-path="tree-based-method.html"><a href="tree-based-method.html#cart-r-pkg-pruning"><i class="fa fa-check"></i><b>8.5.2</b> 가지치기</a></li>
<li class="chapter" data-level="8.5.3" data-path="tree-based-method.html"><a href="tree-based-method.html#cart-r-pkg-param"><i class="fa fa-check"></i><b>8.5.3</b> 파라미터값 결정</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="svm.html"><a href="svm.html"><i class="fa fa-check"></i><b>9</b> 서포트 벡터 머신</a><ul>
<li class="chapter" data-level="9.1" data-path="svm.html"><a href="svm.html#svm-overview"><i class="fa fa-check"></i><b>9.1</b> 개요</a></li>
<li class="chapter" data-level="9.2" data-path="svm.html"><a href="svm.html#svm-packages-install"><i class="fa fa-check"></i><b>9.2</b> 필요 R package 설치</a></li>
<li class="chapter" data-level="9.3" data-path="svm.html"><a href="svm.html#linear-svm-separable"><i class="fa fa-check"></i><b>9.3</b> 선형 SVM - 분리 가능 경우</a><ul>
<li class="chapter" data-level="9.3.1" data-path="svm.html"><a href="svm.html#linear-svm-separable-basic-script"><i class="fa fa-check"></i><b>9.3.1</b> 기본 R 스크립트</a></li>
<li class="chapter" data-level="9.3.2" data-path="svm.html"><a href="svm.html#linear-svm-notation"><i class="fa fa-check"></i><b>9.3.2</b> 기호 정의</a></li>
<li class="chapter" data-level="9.3.3" data-path="svm.html"><a href="svm.html#linear-svm-separable-hyperplane"><i class="fa fa-check"></i><b>9.3.3</b> 최적 하이퍼플레인</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="svm.html"><a href="svm.html#linear-svm-inseparable"><i class="fa fa-check"></i><b>9.4</b> 선형 SVM - 분리 불가능 경우</a><ul>
<li class="chapter" data-level="9.4.1" data-path="svm.html"><a href="svm.html#linear-svm-inseparable-basic-script"><i class="fa fa-check"></i><b>9.4.1</b> 기본 R 스크립트</a></li>
<li class="chapter" data-level="9.4.2" data-path="svm.html"><a href="svm.html#linear-svm-inseparable-hyperplane"><i class="fa fa-check"></i><b>9.4.2</b> 최적 하이퍼플레인</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="svm.html"><a href="svm.html#nonlinear-svm"><i class="fa fa-check"></i><b>9.5</b> 비선형 SVM</a><ul>
<li class="chapter" data-level="9.5.1" data-path="svm.html"><a href="svm.html#nonlinear-svm-basic-script"><i class="fa fa-check"></i><b>9.5.1</b> 기본 R 스크립트</a></li>
<li class="chapter" data-level="9.5.2" data-path="svm.html"><a href="svm.html#nonlinear-svm-hyperplane"><i class="fa fa-check"></i><b>9.5.2</b> 최적 하이퍼플레인</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="svm.html"><a href="svm.html#svm-r-pkg"><i class="fa fa-check"></i><b>9.6</b> R패키지 내 SVM</a><ul>
<li class="chapter" data-level="9.6.1" data-path="svm.html"><a href="svm.html#svm-kernel-function"><i class="fa fa-check"></i><b>9.6.1</b> 커널함수</a></li>
<li class="chapter" data-level="9.6.2" data-path="svm.html"><a href="svm.html#svm-nu-classification"><i class="fa fa-check"></i><b>9.6.2</b> <span class="math inline">\(\nu\)</span>-SVC</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="classifier-evaluation.html"><a href="classifier-evaluation.html"><i class="fa fa-check"></i><b>10</b> 분류규칙의 성능 평가</a><ul>
<li class="chapter" data-level="10.1" data-path="classifier-evaluation.html"><a href="classifier-evaluation.html#classifier-evaluation-packages-install"><i class="fa fa-check"></i><b>10.1</b> 필요 R 패키지 설치</a></li>
<li class="chapter" data-level="10.2" data-path="classifier-evaluation.html"><a href="classifier-evaluation.html#classifier-evaluation-misclassification-rate"><i class="fa fa-check"></i><b>10.2</b> 분류오류율</a></li>
<li class="chapter" data-level="10.3" data-path="classifier-evaluation.html"><a href="classifier-evaluation.html#precision-sensitivity-specificity"><i class="fa fa-check"></i><b>10.3</b> 정확도, 민감도 및 특이도</a><ul>
<li class="chapter" data-level="10.3.1" data-path="classifier-evaluation.html"><a href="classifier-evaluation.html#confusion-matrix-r-package"><i class="fa fa-check"></i><b>10.3.1</b> R 패키지 내 정오분류표</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="classifier-evaluation.html"><a href="classifier-evaluation.html#roc-curve"><i class="fa fa-check"></i><b>10.4</b> ROC 곡선</a></li>
<li class="chapter" data-level="10.5" data-path="classifier-evaluation.html"><a href="classifier-evaluation.html#gain-chart"><i class="fa fa-check"></i><b>10.5</b> 이익도표</a></li>
</ul></li>
<li class="part"><span><b>III 3부 - 군집분석</b></span></li>
<li class="chapter" data-level="11" data-path="clustering-overview.html"><a href="clustering-overview.html"><i class="fa fa-check"></i><b>11</b> 군집분석 개요</a><ul>
<li class="chapter" data-level="11.1" data-path="clustering-overview.html"><a href="clustering-overview.html#clustering-overview-packages-install"><i class="fa fa-check"></i><b>11.1</b> 필요 R 패키지 설치</a></li>
<li class="chapter" data-level="11.2" data-path="clustering-overview.html"><a href="clustering-overview.html#clustering-method"><i class="fa fa-check"></i><b>11.2</b> 군집분석 기법</a></li>
<li class="chapter" data-level="11.3" data-path="clustering-overview.html"><a href="clustering-overview.html#object-similarity-metric"><i class="fa fa-check"></i><b>11.3</b> 객체 간의 유사성 척도</a><ul>
<li class="chapter" data-level="11.3.1" data-path="clustering-overview.html"><a href="clustering-overview.html#object-distance-metric"><i class="fa fa-check"></i><b>11.3.1</b> 거리 관련 척도</a></li>
<li class="chapter" data-level="11.3.2" data-path="clustering-overview.html"><a href="clustering-overview.html#object-correlation-metric"><i class="fa fa-check"></i><b>11.3.2</b> 상관계수 관련 척도</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="clustering-overview.html"><a href="clustering-overview.html#category-similarity-metric"><i class="fa fa-check"></i><b>11.4</b> 범주형 객체의 유사성 척도</a><ul>
<li class="chapter" data-level="11.4.1" data-path="clustering-overview.html"><a href="clustering-overview.html#binary-similarity-metric"><i class="fa fa-check"></i><b>11.4.1</b> 이분형 변수의 경우</a></li>
<li class="chapter" data-level="11.4.2" data-path="clustering-overview.html"><a href="clustering-overview.html#ordinal-similarity-metric"><i class="fa fa-check"></i><b>11.4.2</b> 서열형 변수의 경우</a></li>
<li class="chapter" data-level="11.4.3" data-path="clustering-overview.html"><a href="clustering-overview.html#nominal-similarity-metric"><i class="fa fa-check"></i><b>11.4.3</b> 명목형 변수의 경우</a></li>
<li class="chapter" data-level="11.4.4" data-path="clustering-overview.html"><a href="clustering-overview.html#mixed-similarity-metric"><i class="fa fa-check"></i><b>11.4.4</b> 혼합형의 경우</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="hierarchical-clustering.html"><a href="hierarchical-clustering.html"><i class="fa fa-check"></i><b>12</b> 계층적 군집방법</a><ul>
<li class="chapter" data-level="12.1" data-path="hierarchical-clustering.html"><a href="hierarchical-clustering.html#hierarchical-clustering-packages-install"><i class="fa fa-check"></i><b>12.1</b> 필요 R 패키지 설치</a></li>
<li class="chapter" data-level="12.2" data-path="hierarchical-clustering.html"><a href="hierarchical-clustering.html#distance-between-clusters"><i class="fa fa-check"></i><b>12.2</b> 군집 간 거리척도 및 연결법</a></li>
<li class="chapter" data-level="12.3" data-path="hierarchical-clustering.html"><a href="hierarchical-clustering.html#linkage-method"><i class="fa fa-check"></i><b>12.3</b> 연결법의 군집 알고리즘</a><ul>
<li class="chapter" data-level="12.3.1" data-path="hierarchical-clustering.html"><a href="hierarchical-clustering.html#linkage-method-basic-script"><i class="fa fa-check"></i><b>12.3.1</b> 기본 R 스크립트</a></li>
<li class="chapter" data-level="12.3.2" data-path="hierarchical-clustering.html"><a href="hierarchical-clustering.html#linkage-method-algorithm"><i class="fa fa-check"></i><b>12.3.2</b> 연결법 군집 알고리즘</a></li>
<li class="chapter" data-level="12.3.3" data-path="hierarchical-clustering.html"><a href="hierarchical-clustering.html#hclust"><i class="fa fa-check"></i><b>12.3.3</b> R 패키지 내 연결법</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="hierarchical-clustering.html"><a href="hierarchical-clustering.html#ward-method"><i class="fa fa-check"></i><b>12.4</b> 워드 방법</a><ul>
<li class="chapter" data-level="12.4.1" data-path="hierarchical-clustering.html"><a href="hierarchical-clustering.html#ward-method-basic-script"><i class="fa fa-check"></i><b>12.4.1</b> 기본 R 스크립트</a></li>
<li class="chapter" data-level="12.4.2" data-path="hierarchical-clustering.html"><a href="hierarchical-clustering.html#ward-method-algorithm"><i class="fa fa-check"></i><b>12.4.2</b> 워드 군집 알고리즘</a></li>
<li class="chapter" data-level="12.4.3" data-path="hierarchical-clustering.html"><a href="hierarchical-clustering.html#ward-rpackages"><i class="fa fa-check"></i><b>12.4.3</b> R 패키지 내 워드 방법</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="hierarchical-clustering.html"><a href="hierarchical-clustering.html#diana"><i class="fa fa-check"></i><b>12.5</b> 분리적 방법 - 다이아나</a><ul>
<li class="chapter" data-level="12.5.1" data-path="hierarchical-clustering.html"><a href="hierarchical-clustering.html#diana-basic-script"><i class="fa fa-check"></i><b>12.5.1</b> 기본 R 스크립트</a></li>
<li class="chapter" data-level="12.5.2" data-path="hierarchical-clustering.html"><a href="hierarchical-clustering.html#diana-algorithm"><i class="fa fa-check"></i><b>12.5.2</b> 다이아나 알고리즘</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="hierarchical-clustering.html"><a href="hierarchical-clustering.html#hierarchical-cluster-number"><i class="fa fa-check"></i><b>12.6</b> 군집수의 결정</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html"><i class="fa fa-check"></i><b>13</b> 비계층적 군집방법</a><ul>
<li class="chapter" data-level="13.1" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html#nonhierarchical-clustering-packages-install"><i class="fa fa-check"></i><b>13.1</b> 필요 R package 설치</a></li>
<li class="chapter" data-level="13.2" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html#kmeans"><i class="fa fa-check"></i><b>13.2</b> K-means 알고리즘</a><ul>
<li class="chapter" data-level="13.2.1" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html#kmeans-basic-script"><i class="fa fa-check"></i><b>13.2.1</b> 기본 R 스크립트</a></li>
<li class="chapter" data-level="13.2.2" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html#kmeans-algorithm"><i class="fa fa-check"></i><b>13.2.2</b> 알고리즘</a></li>
<li class="chapter" data-level="13.2.3" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html#kmeans-user-defined-functions"><i class="fa fa-check"></i><b>13.2.3</b> R 스크립트 구현</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html#kmedoids"><i class="fa fa-check"></i><b>13.3</b> K-medoids 군집방법</a><ul>
<li class="chapter" data-level="13.3.1" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html#pam"><i class="fa fa-check"></i><b>13.3.1</b> PAM 알고리즘</a></li>
<li class="chapter" data-level="13.3.2" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html#clara"><i class="fa fa-check"></i><b>13.3.2</b> CLARA 알고리즘</a></li>
<li class="chapter" data-level="13.3.3" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html#clarans"><i class="fa fa-check"></i><b>13.3.3</b> CLARANS 알고리즘</a></li>
<li class="chapter" data-level="13.3.4" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html#kmeans-like"><i class="fa fa-check"></i><b>13.3.4</b> K-means-like 알고리즘</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html#fuzzy-kmeans"><i class="fa fa-check"></i><b>13.4</b> 퍼지 K-means 알고리즘</a><ul>
<li class="chapter" data-level="13.4.1" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html#fuzzy-kmeans-basic-script"><i class="fa fa-check"></i><b>13.4.1</b> 기본 R 스크립트</a></li>
<li class="chapter" data-level="13.4.2" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html#fuzzy-kmeans-algorithm"><i class="fa fa-check"></i><b>13.4.2</b> 알고리즘</a></li>
<li class="chapter" data-level="13.4.3" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html#fuzzy-kmeans-script-implement"><i class="fa fa-check"></i><b>13.4.3</b> R 스크립트 구현</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html#model-based-clustering"><i class="fa fa-check"></i><b>13.5</b> 모형기반 군집방법</a><ul>
<li class="chapter" data-level="13.5.1" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html#model-based-clustering-basic-script"><i class="fa fa-check"></i><b>13.5.1</b> 기본 R script</a></li>
<li class="chapter" data-level="13.5.2" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html#model-based-clustering-em"><i class="fa fa-check"></i><b>13.5.2</b> EM 알고리즘</a></li>
<li class="chapter" data-level="13.5.3" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html#model-based-clustering-script-implement"><i class="fa fa-check"></i><b>13.5.3</b> R 스크립트 구현</a></li>
<li class="chapter" data-level="13.5.4" data-path="nonhierarchical-clustering.html"><a href="nonhierarchical-clustering.html#r-packages-model-based-clustering"><i class="fa fa-check"></i><b>13.5.4</b> R 패키지 내 모형기반 군집분석</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="cluster-solution-evaluation.html"><a href="cluster-solution-evaluation.html"><i class="fa fa-check"></i><b>14</b> 군집해의 평가 및 해석</a><ul>
<li class="chapter" data-level="14.1" data-path="cluster-solution-evaluation.html"><a href="cluster-solution-evaluation.html#cluster-solution-evaluation-packages-install"><i class="fa fa-check"></i><b>14.1</b> 필요 R package 설치</a></li>
<li class="chapter" data-level="14.2" data-path="cluster-solution-evaluation.html"><a href="cluster-solution-evaluation.html#cluster-solution-evaluation-metric"><i class="fa fa-check"></i><b>14.2</b> 군집해의 평가</a><ul>
<li class="chapter" data-level="14.2.1" data-path="cluster-solution-evaluation.html"><a href="cluster-solution-evaluation.html#cluster-evaluation-external-index"><i class="fa fa-check"></i><b>14.2.1</b> 외부평가지수</a></li>
<li class="chapter" data-level="14.2.2" data-path="cluster-solution-evaluation.html"><a href="cluster-solution-evaluation.html#cluster-evaluation-internal-index"><i class="fa fa-check"></i><b>14.2.2</b> 내부평가지수</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="cluster-solution-evaluation.html"><a href="cluster-solution-evaluation.html#cluster-solution-interpretation"><i class="fa fa-check"></i><b>14.3</b> 군집해의 해석</a></li>
</ul></li>
<li class="part"><span><b>IV 4부 - 연관규칙</b></span></li>
<li class="chapter" data-level="15" data-path="association-rule.html"><a href="association-rule.html"><i class="fa fa-check"></i><b>15</b> 연관규칙</a><ul>
<li class="chapter" data-level="15.1" data-path="association-rule.html"><a href="association-rule.html#association-packages-install"><i class="fa fa-check"></i><b>15.1</b> 필요 R package 설치</a></li>
<li class="chapter" data-level="15.2" data-path="association-rule.html"><a href="association-rule.html#association-rule-definition-metric"><i class="fa fa-check"></i><b>15.2</b> 연관규칙의 정의 및 성능척도</a><ul>
<li class="chapter" data-level="15.2.1" data-path="association-rule.html"><a href="association-rule.html#association-rule-support"><i class="fa fa-check"></i><b>15.2.1</b> 지지도</a></li>
<li class="chapter" data-level="15.2.2" data-path="association-rule.html"><a href="association-rule.html#association-rule-confidence"><i class="fa fa-check"></i><b>15.2.2</b> 신뢰도</a></li>
<li class="chapter" data-level="15.2.3" data-path="association-rule.html"><a href="association-rule.html#association-rule-lift"><i class="fa fa-check"></i><b>15.2.3</b> 개선도</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="association-rule.html"><a href="association-rule.html#association-rule-exploration"><i class="fa fa-check"></i><b>15.3</b> 연관규칙의 탐사</a><ul>
<li class="chapter" data-level="15.3.1" data-path="association-rule.html"><a href="association-rule.html#apriori-large-itemsets"><i class="fa fa-check"></i><b>15.3.1</b> 빈발항목집합 생성</a></li>
<li class="chapter" data-level="15.3.2" data-path="association-rule.html"><a href="association-rule.html#apriori-rule-exploration"><i class="fa fa-check"></i><b>15.3.2</b> 규칙의 탐사</a></li>
<li class="chapter" data-level="15.3.3" data-path="association-rule.html"><a href="association-rule.html#apriori-r-package"><i class="fa fa-check"></i><b>15.3.3</b> R 패키지 내 Apriori</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="association-rule.html"><a href="association-rule.html#association-sequential-pattern"><i class="fa fa-check"></i><b>15.4</b> 순차적 패턴의 탐사</a><ul>
<li class="chapter" data-level="15.4.1" data-path="association-rule.html"><a href="association-rule.html#association-aprioriall"><i class="fa fa-check"></i><b>15.4.1</b> AprioriAll 알고리즘</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="recommender-system.html"><a href="recommender-system.html"><i class="fa fa-check"></i><b>16</b> 추천시스템</a><ul>
<li class="chapter" data-level="16.1" data-path="recommender-system.html"><a href="recommender-system.html#recommender-packages-install"><i class="fa fa-check"></i><b>16.1</b> 필요 R package 설치</a></li>
<li class="chapter" data-level="16.2" data-path="recommender-system.html"><a href="recommender-system.html#content-based-recommender"><i class="fa fa-check"></i><b>16.2</b> 내용기반 추천시스템</a></li>
<li class="chapter" data-level="16.3" data-path="recommender-system.html"><a href="recommender-system.html#collaborative-filtering"><i class="fa fa-check"></i><b>16.3</b> 협업 필터링</a></li>
<li class="chapter" data-level="16.4" data-path="recommender-system.html"><a href="recommender-system.html#market-basket"><i class="fa fa-check"></i><b>16.4</b> 시장바구니 데이터를 이용한 협업 필터링</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">데이터마이닝 with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="association-rule" class="section level1">
<h1><span class="header-section-number">Chapter 15</span> 연관규칙</h1>
<div class="sourceCode" id="cb636"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb636-1"><a href="association-rule.html#cb636-1"></a><span class="kw">library</span>(tidyverse)</span></code></pre></div>
<p>연관규칙(association rule)이란 간단히 말하면 항목들 간의 조건-결과 식으로 표현되는 유용한 패턴을 말한다. 연관규칙 탐사는 기업의 활동, 특히 마케팅에서 가장 널리 사용되고 있다.</p>
<div id="association-packages-install" class="section level2">
<h2><span class="header-section-number">15.1</span> 필요 R package 설치</h2>
<p>본 장에서 필요한 R 패키지들은 아래와 같다.</p>
<table>
<thead>
<tr class="header">
<th align="left">package</th>
<th align="left">version</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">tidyverse</td>
<td align="left">1.3.0</td>
</tr>
<tr class="even">
<td align="left">arules</td>
<td align="left">1.6-6</td>
</tr>
</tbody>
</table>
</div>
<div id="association-rule-definition-metric" class="section level2">
<h2><span class="header-section-number">15.2</span> 연관규칙의 정의 및 성능척도</h2>
<p>데이터베이스가 총 <span class="math inline">\(n\)</span>개의 트랜잭션 데이터로 구성되며, 전체 <span class="math inline">\(m\)</span>개의 항목을 포함한다 하자. 전체 항목집합 <span class="math inline">\(I\)</span>를 다음과 같이 정의하자.</p>
<p><span class="math display">\[\begin{equation*}
I = \{ i_1, \cdots, i_m \}
\end{equation*}\]</span></p>
<p>이 때, 각 트랜잭션 <span class="math inline">\(Z_j\)</span>는 <span class="math inline">\(I\)</span>의 부분집합이 된다.</p>
<p><span class="math display">\[\begin{equation*}
Z_j \subseteq I, \, j = 1, \cdots, n
\end{equation*}\]</span></p>
<p>연관규칙 <span class="math inline">\(R\)</span>은 조건부 <span class="math inline">\(X\)</span>와 결과부 <span class="math inline">\(Y\)</span>로 구성되어 (<span class="math inline">\(X, Y \subseteq I\)</span>, <span class="math inline">\(X \cap Y = \emptyset\)</span>) “<span class="math inline">\(X\)</span>가 일어나면 <span class="math inline">\(Y\)</span>도 일어난다”는 의미로 아래와 같이 표현된다.</p>
<p><span class="math display" id="eq:association-rule">\[\begin{equation}
R: X \Rightarrow Y \tag{15.1}
\end{equation}\]</span></p>
<p>식 <a href="association-rule.html#eq:association-rule">(15.1)</a>의 연관규칙 <span class="math inline">\(R\)</span>에 대한 성능척도로 지지도(support), 신뢰도(confidence) 및 개선도(lift)가 널리 사용된다.</p>
<div id="association-rule-support" class="section level3">
<h3><span class="header-section-number">15.2.1</span> 지지도</h3>
<p>지지도는 전체 트랜잭션 중 관심있는 항목집합을 포함하는 트랜잭션의 비율을 나타낸다.</p>
<p>항목 <span class="math inline">\(X \subseteq I\)</span>에 대한 지지도는 아래와 같이 계산된다.</p>
<p><span class="math display">\[\begin{equation*}
supp(X) = \frac{1}{n} \sum_{j = 1}^{n} \mathbb{I}(X \subseteq Z_j)
\end{equation*}\]</span></p>
<p>이 때, <span class="math inline">\(\mathbb{I}(a)\)</span>는 지시함수로 <span class="math inline">\(a\)</span>가 참일 때 1, 거짓일 때 0의 함수값을 가진다.</p>
<p>식 <a href="association-rule.html#eq:association-rule">(15.1)</a>의 연관규칙 <span class="math inline">\(R\)</span>에 대한 지지도는 아래와 같이 정의된다.</p>
<p><span class="math display">\[\begin{equation*}
supp(R) = supp(X \cup Y)
\end{equation*}\]</span></p>
<p>다음과 같은 5개의 트랜잭션을 고려해보자.</p>
<div class="sourceCode" id="cb637"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb637-1"><a href="association-rule.html#cb637-1"></a>transaction_df &lt;-<span class="st"> </span><span class="kw">tribble</span>(</span>
<span id="cb637-2"><a href="association-rule.html#cb637-2"></a>  <span class="op">~</span>transaction_id, <span class="op">~</span>item,</span>
<span id="cb637-3"><a href="association-rule.html#cb637-3"></a>  <span class="dv">1</span>, <span class="st">&quot;b&quot;</span>,</span>
<span id="cb637-4"><a href="association-rule.html#cb637-4"></a>  <span class="dv">1</span>, <span class="st">&quot;c&quot;</span>,</span>
<span id="cb637-5"><a href="association-rule.html#cb637-5"></a>  <span class="dv">1</span>, <span class="st">&quot;g&quot;</span>,</span>
<span id="cb637-6"><a href="association-rule.html#cb637-6"></a>  <span class="dv">2</span>, <span class="st">&quot;a&quot;</span>,</span>
<span id="cb637-7"><a href="association-rule.html#cb637-7"></a>  <span class="dv">2</span>, <span class="st">&quot;b&quot;</span>,</span>
<span id="cb637-8"><a href="association-rule.html#cb637-8"></a>  <span class="dv">2</span>, <span class="st">&quot;d&quot;</span>,</span>
<span id="cb637-9"><a href="association-rule.html#cb637-9"></a>  <span class="dv">2</span>, <span class="st">&quot;e&quot;</span>,</span>
<span id="cb637-10"><a href="association-rule.html#cb637-10"></a>  <span class="dv">2</span>, <span class="st">&quot;f&quot;</span>,</span>
<span id="cb637-11"><a href="association-rule.html#cb637-11"></a>  <span class="dv">3</span>, <span class="st">&quot;a&quot;</span>,</span>
<span id="cb637-12"><a href="association-rule.html#cb637-12"></a>  <span class="dv">3</span>, <span class="st">&quot;b&quot;</span>,</span>
<span id="cb637-13"><a href="association-rule.html#cb637-13"></a>  <span class="dv">3</span>, <span class="st">&quot;c&quot;</span>,</span>
<span id="cb637-14"><a href="association-rule.html#cb637-14"></a>  <span class="dv">3</span>, <span class="st">&quot;g&quot;</span>,</span>
<span id="cb637-15"><a href="association-rule.html#cb637-15"></a>  <span class="dv">4</span>, <span class="st">&quot;b&quot;</span>,</span>
<span id="cb637-16"><a href="association-rule.html#cb637-16"></a>  <span class="dv">4</span>, <span class="st">&quot;c&quot;</span>,</span>
<span id="cb637-17"><a href="association-rule.html#cb637-17"></a>  <span class="dv">4</span>, <span class="st">&quot;e&quot;</span>,</span>
<span id="cb637-18"><a href="association-rule.html#cb637-18"></a>  <span class="dv">4</span>, <span class="st">&quot;f&quot;</span>,</span>
<span id="cb637-19"><a href="association-rule.html#cb637-19"></a>  <span class="dv">5</span>, <span class="st">&quot;b&quot;</span>,</span>
<span id="cb637-20"><a href="association-rule.html#cb637-20"></a>  <span class="dv">5</span>, <span class="st">&quot;c&quot;</span>,</span>
<span id="cb637-21"><a href="association-rule.html#cb637-21"></a>  <span class="dv">5</span>, <span class="st">&quot;e&quot;</span>,</span>
<span id="cb637-22"><a href="association-rule.html#cb637-22"></a>  <span class="dv">5</span>, <span class="st">&quot;f&quot;</span>,</span>
<span id="cb637-23"><a href="association-rule.html#cb637-23"></a>  <span class="dv">5</span>, <span class="st">&quot;g&quot;</span></span>
<span id="cb637-24"><a href="association-rule.html#cb637-24"></a>)</span>
<span id="cb637-25"><a href="association-rule.html#cb637-25"></a></span>
<span id="cb637-26"><a href="association-rule.html#cb637-26"></a>transaction_df <span class="op">%&gt;%</span></span>
<span id="cb637-27"><a href="association-rule.html#cb637-27"></a><span class="st">  </span><span class="kw">group_by</span>(transaction_id) <span class="op">%&gt;%</span></span>
<span id="cb637-28"><a href="association-rule.html#cb637-28"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">items =</span> <span class="kw">str_c</span>(item, <span class="dt">collapse =</span> <span class="st">&quot;, &quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb637-29"><a href="association-rule.html#cb637-29"></a><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>(</span>
<span id="cb637-30"><a href="association-rule.html#cb637-30"></a>    <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</span>
<span id="cb637-31"><a href="association-rule.html#cb637-31"></a>    <span class="dt">align =</span> <span class="kw">c</span>(<span class="st">&#39;c&#39;</span>, <span class="st">&#39;c&#39;</span>),</span>
<span id="cb637-32"><a href="association-rule.html#cb637-32"></a>    <span class="dt">col.names =</span> <span class="kw">c</span>(<span class="st">&#39;트랜잭션&#39;</span>, <span class="st">&#39;항목&#39;</span>),</span>
<span id="cb637-33"><a href="association-rule.html#cb637-33"></a>    <span class="dt">caption =</span> <span class="st">&#39;트랜잭션 데이터&#39;</span></span>
<span id="cb637-34"><a href="association-rule.html#cb637-34"></a>  )</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<table>
<caption><span id="tab:transaction-data">Table 15.1: </span>트랜잭션 데이터</caption>
<thead>
<tr class="header">
<th align="center">트랜잭션</th>
<th align="center">항목</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">b, c, g</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">a, b, d, e, f</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">a, b, c, g</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">b, c, e, f</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">b, c, e, f, g</td>
</tr>
</tbody>
</table>
<p>이 때, 전체 항목집합 <span class="math inline">\(I\)</span>는 <span class="math inline">\(\{a, b, c, d, e, f, g\}\)</span> 이다. 다음과 같은 규칙을 적용해보자.</p>
<p><span class="math display">\[\begin{equation*}
R: \{b, c\} \Rightarrow \{g\}
\end{equation*}\]</span></p>
<p>이 때, 조건부 <span class="math inline">\(X = \{b, c\}\)</span>에 대한 지지도는 아래와 같이 산출된다.</p>
<div class="sourceCode" id="cb639"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb639-1"><a href="association-rule.html#cb639-1"></a>support &lt;-<span class="st"> </span><span class="cf">function</span>(group_df, item, set) {</span>
<span id="cb639-2"><a href="association-rule.html#cb639-2"></a>  <span class="cf">if</span>(<span class="kw">is_empty</span>(set)) <span class="kw">return</span>(<span class="dv">1</span>)</span>
<span id="cb639-3"><a href="association-rule.html#cb639-3"></a>  </span>
<span id="cb639-4"><a href="association-rule.html#cb639-4"></a>  group_df <span class="op">%&gt;%</span></span>
<span id="cb639-5"><a href="association-rule.html#cb639-5"></a><span class="st">    </span><span class="kw">unique</span>() <span class="op">%&gt;%</span></span>
<span id="cb639-6"><a href="association-rule.html#cb639-6"></a><span class="st">    </span><span class="kw">summarize</span>(<span class="dt">n =</span> <span class="kw">sum</span>(<span class="op">!!</span>rlang<span class="op">::</span><span class="kw">sym</span>(item) <span class="op">%in%</span><span class="st"> </span>set)) <span class="op">%&gt;%</span></span>
<span id="cb639-7"><a href="association-rule.html#cb639-7"></a><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">is_support =</span> (n <span class="op">==</span><span class="st"> </span><span class="kw">length</span>(set))) <span class="op">%&gt;%</span></span>
<span id="cb639-8"><a href="association-rule.html#cb639-8"></a><span class="st">    </span>{<span class="kw">mean</span>(.<span class="op">$</span>is_support)}</span>
<span id="cb639-9"><a href="association-rule.html#cb639-9"></a>}</span>
<span id="cb639-10"><a href="association-rule.html#cb639-10"></a></span>
<span id="cb639-11"><a href="association-rule.html#cb639-11"></a>X &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;b&quot;</span>, <span class="st">&quot;c&quot;</span>)</span>
<span id="cb639-12"><a href="association-rule.html#cb639-12"></a>group_transaction_df &lt;-<span class="st"> </span>transaction_df <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(transaction_id)</span>
<span id="cb639-13"><a href="association-rule.html#cb639-13"></a></span>
<span id="cb639-14"><a href="association-rule.html#cb639-14"></a><span class="kw">support</span>(group_transaction_df, <span class="dt">item =</span> <span class="st">&quot;item&quot;</span>, <span class="dt">set =</span> X)</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## [1] 0.8</code></pre>
<p>또한, 규칙 <span class="math inline">\(R\)</span>에 대한 지지도는 아래와 같이 산출할 수 있다.</p>
<div class="sourceCode" id="cb642"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb642-1"><a href="association-rule.html#cb642-1"></a>Y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;g&quot;</span>)</span>
<span id="cb642-2"><a href="association-rule.html#cb642-2"></a><span class="kw">support</span>(group_transaction_df, <span class="dt">item =</span> <span class="st">&quot;item&quot;</span>, <span class="dt">set =</span> <span class="kw">union</span>(X, Y))</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## [1] 0.6</code></pre>
</div>
<div id="association-rule-confidence" class="section level3">
<h3><span class="header-section-number">15.2.2</span> 신뢰도</h3>
<p>연관규칙 <span class="math inline">\(R\)</span>의 가치를 평가할 때, 통상 다음과 같이 정의되는 신뢰도를 사용한다.</p>
<p><span class="math display">\[\begin{equation*}
conf(R) = \frac{supp(R)}{supp(X)} = \frac{supp(X \cup Y)}{supp(X)}
\end{equation*}\]</span></p>
<p>이 신뢰도는 조건부 확률의 개념으로, 집합 <span class="math inline">\(X\)</span>(조건부)가 발생할 때 집합 <span class="math inline">\(Y\)</span>(결과부)도 동시에 발생할 확률을 의미한다.</p>
<div class="sourceCode" id="cb645"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb645-1"><a href="association-rule.html#cb645-1"></a>rule_confidence &lt;-<span class="st"> </span><span class="cf">function</span>(group_df, item, x, y) {</span>
<span id="cb645-2"><a href="association-rule.html#cb645-2"></a>  <span class="kw">support</span>(group_df, item, <span class="kw">union</span>(x, y)) <span class="op">/</span><span class="st"> </span><span class="kw">support</span>(group_df, item, x)</span>
<span id="cb645-3"><a href="association-rule.html#cb645-3"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb646"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb646-1"><a href="association-rule.html#cb646-1"></a><span class="kw">rule_confidence</span>(group_transaction_df, <span class="dt">item =</span> <span class="st">&quot;item&quot;</span>, <span class="dt">x =</span> X, <span class="dt">y =</span> Y)</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## [1] 0.75</code></pre>
</div>
<div id="association-rule-lift" class="section level3">
<h3><span class="header-section-number">15.2.3</span> 개선도</h3>
<p>결과가 단독으로 발생할 가능성에 비추어 조건과 연계하여 결과가 발생할 가능성의 빈도 비율로 정의한다.</p>
<p><span class="math display">\[\begin{equation*}
lift(R) = \frac{conf(R)}{supp(Y)} = \frac{supp(X \cup Y)}{supp(X)supp(Y)}
\end{equation*}\]</span></p>
<div class="sourceCode" id="cb649"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb649-1"><a href="association-rule.html#cb649-1"></a>rule_lift &lt;-<span class="st"> </span><span class="cf">function</span>(group_df, item, x, y) {</span>
<span id="cb649-2"><a href="association-rule.html#cb649-2"></a>  <span class="kw">rule_confidence</span>(group_df, item, x, y) <span class="op">/</span><span class="st"> </span><span class="kw">support</span>(group_df, item, y)</span>
<span id="cb649-3"><a href="association-rule.html#cb649-3"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb650"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb650-1"><a href="association-rule.html#cb650-1"></a><span class="kw">rule_lift</span>(group_transaction_df, <span class="dt">item =</span> <span class="st">&quot;item&quot;</span>, <span class="dt">x =</span> X, <span class="dt">y =</span> Y)</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## [1] 1.25</code></pre>
<p>즉, 항목 <span class="math inline">\(b\)</span>, <span class="math inline">\(c\)</span>가 발생할 때 <span class="math inline">\(g\)</span>가 발생하는 빈도가 25% 높아진다.</p>
</div>
</div>
<div id="association-rule-exploration" class="section level2">
<h2><span class="header-section-number">15.3</span> 연관규칙의 탐사</h2>
<p>연관규칙의 탐사는 결국 신뢰도 또는 개선도가 높은 규칙 <span class="math inline">\(R\)</span>을 트랜잭션 데이터로부터 도출하는 과정이다. 알고리즘으로 가장 널리 사용되는 것이 Apriori 알고리즘<span class="citation">(Agrawal, Srikant, and others <a href="#ref-agrawal1994fast" role="doc-biblioref">1994</a>)</span>이다.</p>
<div id="apriori-large-itemsets" class="section level3">
<h3><span class="header-section-number">15.3.1</span> 빈발항목집합 생성</h3>
<p>빈발항목집합(large itemsets)이란 미리 결정한 최소 지지도 <span class="math inline">\(s_{\text{min}}\)</span> 이상의 지지도를 같는 모든 항목집합들을 뜻한다.</p>
<p>빈발항목집합 생성 과정은 아래와 같다.</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(k\)</span>개의 항목을 지닌 빈발항목집합 후보군 <span class="math inline">\(C_{k}\)</span> 중 최소지지도 <span class="math inline">\(s_{\text{min}}\)</span> 이상의 지지도를 같는 모든 항목집합들을 빈발항목집합 <span class="math inline">\(L_{k}\)</span>라 한다.</li>
<li>빈발항목집합들 <span class="math inline">\(L_{k}\)</span>내의 각 쌍에 대해 합집합을 구하여 그 합집합의 크기(항목의 수)가 <span class="math inline">\(k + 1\)</span>인 항목집합들을 빈발항목집합 후보군 <span class="math inline">\(C_{k + 1}\)</span>라 한다.</li>
</ol>
<p><span class="math inline">\(k\)</span>를 1부터 증가시키면서 더 이상 빈발항목집합을 찾을 수 없을 때까지 위 과정을 반복한다. 이 때, 빈발항목집합 후보군을 생성하는 함수 <code>apriori_gen</code>을 아래와 같이 구현해보자.</p>
<div class="sourceCode" id="cb653"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb653-1"><a href="association-rule.html#cb653-1"></a>apriori_gen &lt;-<span class="st"> </span><span class="cf">function</span>(L) {</span>
<span id="cb653-2"><a href="association-rule.html#cb653-2"></a>  <span class="cf">if</span>(<span class="kw">length</span>(L) <span class="op">&lt;</span><span class="st"> </span><span class="dv">2</span>) <span class="kw">return</span>(<span class="ot">NULL</span>)</span>
<span id="cb653-3"><a href="association-rule.html#cb653-3"></a>  </span>
<span id="cb653-4"><a href="association-rule.html#cb653-4"></a>  n_sets &lt;-<span class="st"> </span><span class="kw">length</span>(L)</span>
<span id="cb653-5"><a href="association-rule.html#cb653-5"></a>  n_item &lt;-<span class="st"> </span><span class="kw">unique</span>(<span class="kw">map_dbl</span>(L, length))</span>
<span id="cb653-6"><a href="association-rule.html#cb653-6"></a></span>
<span id="cb653-7"><a href="association-rule.html#cb653-7"></a>  <span class="cf">if</span>(<span class="kw">length</span>(n_item) <span class="op">&gt;</span><span class="st"> </span><span class="dv">1</span>) <span class="kw">stop</span>(<span class="st">&quot;All itemsets must be the same length.&quot;</span>)</span>
<span id="cb653-8"><a href="association-rule.html#cb653-8"></a>  </span>
<span id="cb653-9"><a href="association-rule.html#cb653-9"></a>  C &lt;-<span class="st"> </span><span class="kw">combn</span>(L, <span class="dt">m =</span> <span class="dv">2</span>, <span class="dt">simplify =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb653-10"><a href="association-rule.html#cb653-10"></a><span class="st">    </span><span class="kw">t</span>() <span class="op">%&gt;%</span></span>
<span id="cb653-11"><a href="association-rule.html#cb653-11"></a><span class="st">    `</span><span class="dt">colnames&lt;-</span><span class="st">`</span>(<span class="kw">c</span>(<span class="st">&quot;set1&quot;</span>, <span class="st">&quot;set2&quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb653-12"><a href="association-rule.html#cb653-12"></a><span class="st">    </span><span class="kw">as_tibble</span>() <span class="op">%&gt;%</span></span>
<span id="cb653-13"><a href="association-rule.html#cb653-13"></a><span class="st">    </span><span class="kw">pmap</span>(<span class="cf">function</span>(set1, set2) {</span>
<span id="cb653-14"><a href="association-rule.html#cb653-14"></a>      <span class="cf">if</span>(<span class="kw">length</span>(<span class="kw">intersect</span>(set1, set2)) <span class="op">!=</span><span class="st"> </span>n_item <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="kw">return</span>(<span class="ot">NULL</span>)</span>
<span id="cb653-15"><a href="association-rule.html#cb653-15"></a>      <span class="kw">sort</span>(<span class="kw">union</span>(set1, set2))</span>
<span id="cb653-16"><a href="association-rule.html#cb653-16"></a>      }) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb653-17"><a href="association-rule.html#cb653-17"></a><span class="st">    </span><span class="kw">compact</span>() <span class="op">%&gt;%</span></span>
<span id="cb653-18"><a href="association-rule.html#cb653-18"></a><span class="st">    </span><span class="kw">unique</span>()</span>
<span id="cb653-19"><a href="association-rule.html#cb653-19"></a></span>
<span id="cb653-20"><a href="association-rule.html#cb653-20"></a>  C  </span>
<span id="cb653-21"><a href="association-rule.html#cb653-21"></a>}</span></code></pre></div>
<p>위 함수를 이용하여, Table <a href="association-rule.html#tab:transaction-data">15.1</a>에서 최소 지지도 <span class="math inline">\(s_{\text{min}} = 0.4\)</span>를 기준으로 빈발항목집합을 찾아보자.</p>
<div class="sourceCode" id="cb654"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb654-1"><a href="association-rule.html#cb654-1"></a>s_min &lt;-<span class="st"> </span><span class="fl">0.4</span></span>
<span id="cb654-2"><a href="association-rule.html#cb654-2"></a>group_transaction_df &lt;-<span class="st"> </span>transaction_df <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(transaction_id)</span>
<span id="cb654-3"><a href="association-rule.html#cb654-3"></a></span>
<span id="cb654-4"><a href="association-rule.html#cb654-4"></a>candidate_itemsets &lt;-<span class="st"> </span><span class="kw">as.list</span>(<span class="kw">sort</span>(<span class="kw">unique</span>(transaction_df<span class="op">$</span>item)))</span>
<span id="cb654-5"><a href="association-rule.html#cb654-5"></a>large_itemsets &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&quot;list&quot;</span>, <span class="dt">length =</span> <span class="kw">length</span>(candidate_itemsets))</span>
<span id="cb654-6"><a href="association-rule.html#cb654-6"></a></span>
<span id="cb654-7"><a href="association-rule.html#cb654-7"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="kw">seq_along</span>(large_itemsets)) {</span>
<span id="cb654-8"><a href="association-rule.html#cb654-8"></a>  itemset_support &lt;-<span class="st"> </span><span class="kw">map_dbl</span>(candidate_itemsets, </span>
<span id="cb654-9"><a href="association-rule.html#cb654-9"></a>                             support, </span>
<span id="cb654-10"><a href="association-rule.html#cb654-10"></a>                             <span class="dt">group_df =</span> group_transaction_df, </span>
<span id="cb654-11"><a href="association-rule.html#cb654-11"></a>                             <span class="dt">item =</span> <span class="st">&quot;item&quot;</span>)</span>
<span id="cb654-12"><a href="association-rule.html#cb654-12"></a></span>
<span id="cb654-13"><a href="association-rule.html#cb654-13"></a>  large_itemsets[[i]] &lt;-<span class="st"> </span>candidate_itemsets[itemset_support <span class="op">&gt;=</span><span class="st"> </span>s_min]</span>
<span id="cb654-14"><a href="association-rule.html#cb654-14"></a>  </span>
<span id="cb654-15"><a href="association-rule.html#cb654-15"></a>  candidate_itemsets &lt;-<span class="st"> </span><span class="kw">apriori_gen</span>(large_itemsets[[i]])</span>
<span id="cb654-16"><a href="association-rule.html#cb654-16"></a>  </span>
<span id="cb654-17"><a href="association-rule.html#cb654-17"></a>  <span class="cf">if</span>(<span class="kw">is.null</span>(candidate_itemsets)) <span class="cf">break</span></span>
<span id="cb654-18"><a href="association-rule.html#cb654-18"></a>}</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb656"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb656-1"><a href="association-rule.html#cb656-1"></a>large_itemsets &lt;-<span class="st"> </span><span class="kw">compact</span>(large_itemsets)</span></code></pre></div>
<p>찾아진 빈발항목집합들은 아래와 같다.</p>
<div class="sourceCode" id="cb657"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb657-1"><a href="association-rule.html#cb657-1"></a><span class="kw">map</span>(large_itemsets,</span>
<span id="cb657-2"><a href="association-rule.html#cb657-2"></a>    <span class="op">~</span><span class="kw">map_chr</span>(.x, <span class="op">~</span><span class="kw">str_c</span>(<span class="st">&quot;{&quot;</span>, <span class="kw">str_c</span>(.x, <span class="dt">collapse =</span> <span class="st">&quot;, &quot;</span>), <span class="st">&quot;}&quot;</span>)))</span></code></pre></div>
<pre><code>## [[1]]
## [1] &quot;{a}&quot; &quot;{b}&quot; &quot;{c}&quot; &quot;{e}&quot; &quot;{f}&quot; &quot;{g}&quot;
## 
## [[2]]
## [1] &quot;{a, b}&quot; &quot;{b, c}&quot; &quot;{b, e}&quot; &quot;{b, f}&quot; &quot;{b, g}&quot; &quot;{c, e}&quot; &quot;{c, f}&quot; &quot;{c, g}&quot; &quot;{e, f}&quot;
## 
## [[3]]
## [1] &quot;{b, c, e}&quot; &quot;{b, c, f}&quot; &quot;{b, c, g}&quot; &quot;{b, e, f}&quot; &quot;{c, e, f}&quot;
## 
## [[4]]
## [1] &quot;{b, c, e, f}&quot;</code></pre>
</div>
<div id="apriori-rule-exploration" class="section level3">
<h3><span class="header-section-number">15.3.2</span> 규칙의 탐사</h3>
<p>도출된 빈발항목집합 각각(<span class="math inline">\(L\)</span>)을 조건부(<span class="math inline">\(X\)</span>)와 결과부(<span class="math inline">\(Y = L \backslash A\)</span>)로 나눌 때 미리 결정된 최소 신뢰도 <span class="math inline">\(c_{\text{min}}\)</span> 이상의 신뢰도를 지닌 규칙 <span class="math inline">\(R\)</span>을 찾는다.</p>
<p><span class="math display">\[\begin{equation*}
R: X \Rightarrow L \backslash X
\end{equation*}\]</span></p>
<p>우선, 빈발항목집합 <span class="math inline">\(L\)</span>으로부터 가능한 규칙들을 생성하는 함수 <code>generate_rules</code>를 아래와 같이 구현해보자.</p>
<div class="sourceCode" id="cb659"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb659-1"><a href="association-rule.html#cb659-1"></a>generate_rules &lt;-<span class="st"> </span><span class="cf">function</span>(L, <span class="dt">n_min_item =</span> <span class="dv">1</span>) {</span>
<span id="cb659-2"><a href="association-rule.html#cb659-2"></a>  n_item &lt;-<span class="st"> </span><span class="kw">length</span>(L)</span>
<span id="cb659-3"><a href="association-rule.html#cb659-3"></a>  <span class="cf">if</span>(n_item <span class="op">&lt;</span><span class="st"> </span>n_min_item) <span class="kw">return</span>(<span class="ot">NULL</span>) <span class="co"># 항목 최소개수 제한</span></span>
<span id="cb659-4"><a href="association-rule.html#cb659-4"></a>  </span>
<span id="cb659-5"><a href="association-rule.html#cb659-5"></a>  X &lt;-<span class="st"> </span><span class="kw">map</span>(<span class="kw">seq_len</span>(n_item), <span class="op">~</span><span class="kw">combn</span>(L, <span class="dt">m =</span> .x <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, list)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">flatten</span>()</span>
<span id="cb659-6"><a href="association-rule.html#cb659-6"></a>  Y &lt;-<span class="st"> </span><span class="kw">map</span>(X, <span class="op">~</span><span class="kw">setdiff</span>(L, .x))</span>
<span id="cb659-7"><a href="association-rule.html#cb659-7"></a>  </span>
<span id="cb659-8"><a href="association-rule.html#cb659-8"></a>  <span class="kw">tibble</span>(<span class="dt">X =</span> X, <span class="dt">Y =</span> Y)</span>
<span id="cb659-9"><a href="association-rule.html#cb659-9"></a>}</span></code></pre></div>
<p>앞 장에서 추출한 모든 빈발항목집합들로부터 규칙을 생성해보자.</p>
<div class="sourceCode" id="cb660"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb660-1"><a href="association-rule.html#cb660-1"></a>rule_list &lt;-<span class="st"> </span><span class="kw">map_dfr</span>(</span>
<span id="cb660-2"><a href="association-rule.html#cb660-2"></a>  large_itemsets <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">flatten</span>(),</span>
<span id="cb660-3"><a href="association-rule.html#cb660-3"></a>  generate_rules</span>
<span id="cb660-4"><a href="association-rule.html#cb660-4"></a>)</span></code></pre></div>
<p>각각의 규칙에 대하여 신뢰도를 계산하여, 그 값이 최소 신뢰도 <span class="math inline">\(c_{\text{min}}\)</span> 이상인 규칙만을 <code>conf_rule_list</code>라는 데이터 프레임으로 저장하자.</p>
<div class="sourceCode" id="cb661"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb661-1"><a href="association-rule.html#cb661-1"></a>rule_list<span class="op">$</span>confidence &lt;-<span class="st"> </span><span class="kw">pmap_dbl</span>(rule_list, <span class="cf">function</span>(X, Y) </span>
<span id="cb661-2"><a href="association-rule.html#cb661-2"></a>  <span class="kw">rule_confidence</span>(group_transaction_df, <span class="dt">item =</span> <span class="st">&quot;item&quot;</span>, <span class="dt">x =</span> X, <span class="dt">y =</span> Y)</span>
<span id="cb661-3"><a href="association-rule.html#cb661-3"></a>  )</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)
## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb663"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb663-1"><a href="association-rule.html#cb663-1"></a>c_min &lt;-<span class="st"> </span><span class="fl">0.7</span></span>
<span id="cb663-2"><a href="association-rule.html#cb663-2"></a>conf_rule_list &lt;-<span class="st"> </span>rule_list <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(confidence <span class="op">&gt;=</span><span class="st"> </span>c_min)</span></code></pre></div>
<p>이 결과 최종적으로 도출된 규칙들은 아래와 같다.</p>
<div class="sourceCode" id="cb664"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb664-1"><a href="association-rule.html#cb664-1"></a>conf_rule_list <span class="op">%&gt;%</span></span>
<span id="cb664-2"><a href="association-rule.html#cb664-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span></span>
<span id="cb664-3"><a href="association-rule.html#cb664-3"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb664-4"><a href="association-rule.html#cb664-4"></a>    <span class="dt">X =</span> <span class="kw">str_c</span>(<span class="st">&quot;{&quot;</span>, <span class="kw">str_c</span>(<span class="kw">unlist</span>(X), <span class="dt">collapse =</span> <span class="st">&quot;, &quot;</span>), <span class="st">&quot;}&quot;</span>),</span>
<span id="cb664-5"><a href="association-rule.html#cb664-5"></a>    <span class="dt">Y =</span> <span class="kw">str_c</span>(<span class="st">&quot;{&quot;</span>, <span class="kw">str_c</span>(<span class="kw">unlist</span>(Y), <span class="dt">collapse =</span> <span class="st">&quot;, &quot;</span>), <span class="st">&quot;}&quot;</span>)</span>
<span id="cb664-6"><a href="association-rule.html#cb664-6"></a>  ) <span class="op">%&gt;%</span></span>
<span id="cb664-7"><a href="association-rule.html#cb664-7"></a><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>(</span>
<span id="cb664-8"><a href="association-rule.html#cb664-8"></a>    <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</span>
<span id="cb664-9"><a href="association-rule.html#cb664-9"></a>    <span class="dt">align =</span> <span class="kw">c</span>(<span class="st">&#39;c&#39;</span>, <span class="st">&#39;c&#39;</span>, <span class="st">&#39;c&#39;</span>),</span>
<span id="cb664-10"><a href="association-rule.html#cb664-10"></a>    <span class="dt">col.names =</span> <span class="kw">c</span>(<span class="st">&#39;조건부 $X$&#39;</span>, <span class="st">&#39;결과부 $Y$&#39;</span>, <span class="st">&#39;신뢰도&#39;</span>),</span>
<span id="cb664-11"><a href="association-rule.html#cb664-11"></a>    <span class="dt">caption =</span> <span class="st">&#39;최종 연관규칙&#39;</span></span>
<span id="cb664-12"><a href="association-rule.html#cb664-12"></a>  )</span></code></pre></div>
<table>
<caption><span id="tab:confident-rules">Table 15.2: </span>최종 연관규칙</caption>
<thead>
<tr class="header">
<th align="center">조건부 <span class="math inline">\(X\)</span></th>
<th align="center">결과부 <span class="math inline">\(Y\)</span></th>
<th align="center">신뢰도</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">{}</td>
<td align="center">{b}</td>
<td align="center">1.00</td>
</tr>
<tr class="even">
<td align="center">{}</td>
<td align="center">{c}</td>
<td align="center">0.80</td>
</tr>
<tr class="odd">
<td align="center">{a}</td>
<td align="center">{b}</td>
<td align="center">1.00</td>
</tr>
<tr class="even">
<td align="center">{}</td>
<td align="center">{b, c}</td>
<td align="center">0.80</td>
</tr>
<tr class="odd">
<td align="center">{b}</td>
<td align="center">{c}</td>
<td align="center">0.80</td>
</tr>
<tr class="even">
<td align="center">{c}</td>
<td align="center">{b}</td>
<td align="center">1.00</td>
</tr>
<tr class="odd">
<td align="center">{e}</td>
<td align="center">{b}</td>
<td align="center">1.00</td>
</tr>
<tr class="even">
<td align="center">{f}</td>
<td align="center">{b}</td>
<td align="center">1.00</td>
</tr>
<tr class="odd">
<td align="center">{g}</td>
<td align="center">{b}</td>
<td align="center">1.00</td>
</tr>
<tr class="even">
<td align="center">{c}</td>
<td align="center">{g}</td>
<td align="center">0.75</td>
</tr>
<tr class="odd">
<td align="center">{g}</td>
<td align="center">{c}</td>
<td align="center">1.00</td>
</tr>
<tr class="even">
<td align="center">{e}</td>
<td align="center">{f}</td>
<td align="center">1.00</td>
</tr>
<tr class="odd">
<td align="center">{f}</td>
<td align="center">{e}</td>
<td align="center">1.00</td>
</tr>
<tr class="even">
<td align="center">{c, e}</td>
<td align="center">{b}</td>
<td align="center">1.00</td>
</tr>
<tr class="odd">
<td align="center">{c, f}</td>
<td align="center">{b}</td>
<td align="center">1.00</td>
</tr>
<tr class="even">
<td align="center">{c}</td>
<td align="center">{b, g}</td>
<td align="center">0.75</td>
</tr>
<tr class="odd">
<td align="center">{g}</td>
<td align="center">{b, c}</td>
<td align="center">1.00</td>
</tr>
<tr class="even">
<td align="center">{b, c}</td>
<td align="center">{g}</td>
<td align="center">0.75</td>
</tr>
<tr class="odd">
<td align="center">{b, g}</td>
<td align="center">{c}</td>
<td align="center">1.00</td>
</tr>
<tr class="even">
<td align="center">{c, g}</td>
<td align="center">{b}</td>
<td align="center">1.00</td>
</tr>
<tr class="odd">
<td align="center">{e}</td>
<td align="center">{b, f}</td>
<td align="center">1.00</td>
</tr>
<tr class="even">
<td align="center">{f}</td>
<td align="center">{b, e}</td>
<td align="center">1.00</td>
</tr>
<tr class="odd">
<td align="center">{b, e}</td>
<td align="center">{f}</td>
<td align="center">1.00</td>
</tr>
<tr class="even">
<td align="center">{b, f}</td>
<td align="center">{e}</td>
<td align="center">1.00</td>
</tr>
<tr class="odd">
<td align="center">{e, f}</td>
<td align="center">{b}</td>
<td align="center">1.00</td>
</tr>
<tr class="even">
<td align="center">{c, e}</td>
<td align="center">{f}</td>
<td align="center">1.00</td>
</tr>
<tr class="odd">
<td align="center">{c, f}</td>
<td align="center">{e}</td>
<td align="center">1.00</td>
</tr>
<tr class="even">
<td align="center">{c, e}</td>
<td align="center">{b, f}</td>
<td align="center">1.00</td>
</tr>
<tr class="odd">
<td align="center">{c, f}</td>
<td align="center">{b, e}</td>
<td align="center">1.00</td>
</tr>
<tr class="even">
<td align="center">{b, c, e}</td>
<td align="center">{f}</td>
<td align="center">1.00</td>
</tr>
<tr class="odd">
<td align="center">{b, c, f}</td>
<td align="center">{e}</td>
<td align="center">1.00</td>
</tr>
<tr class="even">
<td align="center">{c, e, f}</td>
<td align="center">{b}</td>
<td align="center">1.00</td>
</tr>
</tbody>
</table>
<p>항목의 수가 많은 경우, 생성 가능한 규칙의 수가 매우 많아, 보다 효율적인 탐사의 수행이 필요할 수 있다. 자세한 방법에 대해서는 교재 <span class="citation">(전치혁 <a href="#ref-jun2012datamining" role="doc-biblioref">2012</a>)</span> 참조.</p>
</div>
<div id="apriori-r-package" class="section level3">
<h3><span class="header-section-number">15.3.3</span> R 패키지 내 Apriori</h3>
<p>R 패키지 <code>arules</code>의 <code>apriori</code> 함수를 이용하여 위에서 살펴본 연관규칙 탐사를 수행할 수 있다.</p>
<p>우선, <a href="association-rule.html#association-rule-support">15.2.1</a> 절에서 생성한 데이터 프레임 <code>transaction_df</code>를 <code>arules</code> 패키지 내에 정의된 <code>transactions</code> 클래스 형태의 데이터로 변환한다.</p>
<div class="sourceCode" id="cb665"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb665-1"><a href="association-rule.html#cb665-1"></a><span class="kw">requireNamespace</span>(<span class="st">&quot;arules&quot;</span>)</span></code></pre></div>
<pre><code>## Loading required namespace: arules</code></pre>
<div class="sourceCode" id="cb667"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb667-1"><a href="association-rule.html#cb667-1"></a>transaction_df2 &lt;-<span class="st"> </span><span class="kw">as</span>(</span>
<span id="cb667-2"><a href="association-rule.html#cb667-2"></a>  <span class="kw">split</span>(transaction_df<span class="op">$</span>item, transaction_df<span class="op">$</span>transaction_id),</span>
<span id="cb667-3"><a href="association-rule.html#cb667-3"></a>  <span class="st">&quot;transactions&quot;</span></span>
<span id="cb667-4"><a href="association-rule.html#cb667-4"></a>)</span></code></pre></div>
<p>이후, <code>apriori</code> 함수를 호출하여 연관규칙 탐사를 수행한다.</p>
<div class="sourceCode" id="cb668"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb668-1"><a href="association-rule.html#cb668-1"></a>rule_results &lt;-<span class="st"> </span>arules<span class="op">::</span><span class="kw">apriori</span>(</span>
<span id="cb668-2"><a href="association-rule.html#cb668-2"></a>  transaction_df2,</span>
<span id="cb668-3"><a href="association-rule.html#cb668-3"></a>  <span class="dt">parameter =</span> <span class="kw">list</span>(</span>
<span id="cb668-4"><a href="association-rule.html#cb668-4"></a>    <span class="dt">support =</span> <span class="fl">0.4</span>,</span>
<span id="cb668-5"><a href="association-rule.html#cb668-5"></a>    <span class="dt">confidence =</span> <span class="fl">0.7</span>,</span>
<span id="cb668-6"><a href="association-rule.html#cb668-6"></a>    <span class="dt">target =</span> <span class="st">&quot;rules&quot;</span></span>
<span id="cb668-7"><a href="association-rule.html#cb668-7"></a>  ),</span>
<span id="cb668-8"><a href="association-rule.html#cb668-8"></a>  <span class="dt">control =</span> <span class="kw">list</span>(</span>
<span id="cb668-9"><a href="association-rule.html#cb668-9"></a>    <span class="dt">verbose =</span> <span class="ot">FALSE</span></span>
<span id="cb668-10"><a href="association-rule.html#cb668-10"></a>  )</span>
<span id="cb668-11"><a href="association-rule.html#cb668-11"></a>)</span></code></pre></div>
<p>결과로 얻어지는 <code>rules</code> 클래스 객체에서 필요한 정보를 추출하여 데이터 프레임으로 저장하자.</p>
<ul>
<li><code>lhs</code>: 조건부</li>
<li><code>rhs</code>: 결과부</li>
<li><code>quality</code>: 평가척도 (지지도, 신뢰도, 개선도, 관측수)</li>
</ul>
<div class="sourceCode" id="cb669"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb669-1"><a href="association-rule.html#cb669-1"></a>rule_results_df &lt;-<span class="st"> </span><span class="kw">tibble</span>(</span>
<span id="cb669-2"><a href="association-rule.html#cb669-2"></a>  <span class="dt">X =</span> <span class="kw">as</span>(rule_results<span class="op">@</span>lhs, <span class="st">&quot;list&quot;</span>),</span>
<span id="cb669-3"><a href="association-rule.html#cb669-3"></a>  <span class="dt">Y =</span> <span class="kw">as</span>(rule_results<span class="op">@</span>rhs, <span class="st">&quot;list&quot;</span>)</span>
<span id="cb669-4"><a href="association-rule.html#cb669-4"></a>) <span class="op">%&gt;%</span></span>
<span id="cb669-5"><a href="association-rule.html#cb669-5"></a><span class="st">  </span><span class="kw">bind_cols</span>(rule_results<span class="op">@</span>quality)</span></code></pre></div>
<p>해당 데이터 프레임은 아래와 같다.</p>
<div class="sourceCode" id="cb670"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb670-1"><a href="association-rule.html#cb670-1"></a>rule_results_df <span class="op">%&gt;%</span></span>
<span id="cb670-2"><a href="association-rule.html#cb670-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span></span>
<span id="cb670-3"><a href="association-rule.html#cb670-3"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb670-4"><a href="association-rule.html#cb670-4"></a>    <span class="dt">X =</span> <span class="kw">str_c</span>(<span class="st">&quot;{&quot;</span>, <span class="kw">str_c</span>(<span class="kw">unlist</span>(X), <span class="dt">collapse =</span> <span class="st">&quot;, &quot;</span>), <span class="st">&quot;}&quot;</span>),</span>
<span id="cb670-5"><a href="association-rule.html#cb670-5"></a>    <span class="dt">Y =</span> <span class="kw">str_c</span>(<span class="st">&quot;{&quot;</span>, <span class="kw">str_c</span>(<span class="kw">unlist</span>(Y), <span class="dt">collapse =</span> <span class="st">&quot;, &quot;</span>), <span class="st">&quot;}&quot;</span>)</span>
<span id="cb670-6"><a href="association-rule.html#cb670-6"></a>  ) <span class="op">%&gt;%</span></span>
<span id="cb670-7"><a href="association-rule.html#cb670-7"></a><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>(</span>
<span id="cb670-8"><a href="association-rule.html#cb670-8"></a>    <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</span>
<span id="cb670-9"><a href="association-rule.html#cb670-9"></a>    <span class="dt">align =</span> <span class="kw">c</span>(<span class="st">&#39;c&#39;</span>, <span class="st">&#39;c&#39;</span>, <span class="st">&#39;c&#39;</span>, <span class="st">&#39;c&#39;</span>, <span class="st">&#39;c&#39;</span>, <span class="st">&#39;c&#39;</span>, <span class="st">&#39;c&#39;</span>),</span>
<span id="cb670-10"><a href="association-rule.html#cb670-10"></a>    <span class="dt">col.names =</span> <span class="kw">c</span>(<span class="st">&#39;조건부 $X$&#39;</span>, <span class="st">&#39;결과부 $Y$&#39;</span>, <span class="st">&#39;지지도&#39;</span>,</span>
<span id="cb670-11"><a href="association-rule.html#cb670-11"></a>                  <span class="st">&#39;신뢰도&#39;</span>, <span class="st">&#39;포함률&#39;</span>, <span class="st">&#39;개선도&#39;</span>, <span class="st">&#39;관측수&#39;</span>),</span>
<span id="cb670-12"><a href="association-rule.html#cb670-12"></a>    <span class="dt">caption =</span> <span class="st">&#39;최종 연관규칙 - arules::apriori&#39;</span></span>
<span id="cb670-13"><a href="association-rule.html#cb670-13"></a>  )</span></code></pre></div>
<table>
<caption><span id="tab:apriori-r-results">Table 15.3: </span>최종 연관규칙 - arules::apriori</caption>
<thead>
<tr class="header">
<th align="center">조건부 <span class="math inline">\(X\)</span></th>
<th align="center">결과부 <span class="math inline">\(Y\)</span></th>
<th align="center">지지도</th>
<th align="center">신뢰도</th>
<th align="center">포함률</th>
<th align="center">개선도</th>
<th align="center">관측수</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">{}</td>
<td align="center">{c}</td>
<td align="center">0.8</td>
<td align="center">0.80</td>
<td align="center">1.0</td>
<td align="center">1.000000</td>
<td align="center">4</td>
</tr>
<tr class="even">
<td align="center">{}</td>
<td align="center">{b}</td>
<td align="center">1.0</td>
<td align="center">1.00</td>
<td align="center">1.0</td>
<td align="center">1.000000</td>
<td align="center">5</td>
</tr>
<tr class="odd">
<td align="center">{a}</td>
<td align="center">{b}</td>
<td align="center">0.4</td>
<td align="center">1.00</td>
<td align="center">0.4</td>
<td align="center">1.000000</td>
<td align="center">2</td>
</tr>
<tr class="even">
<td align="center">{g}</td>
<td align="center">{c}</td>
<td align="center">0.6</td>
<td align="center">1.00</td>
<td align="center">0.6</td>
<td align="center">1.250000</td>
<td align="center">3</td>
</tr>
<tr class="odd">
<td align="center">{c}</td>
<td align="center">{g}</td>
<td align="center">0.6</td>
<td align="center">0.75</td>
<td align="center">0.8</td>
<td align="center">1.250000</td>
<td align="center">3</td>
</tr>
<tr class="even">
<td align="center">{g}</td>
<td align="center">{b}</td>
<td align="center">0.6</td>
<td align="center">1.00</td>
<td align="center">0.6</td>
<td align="center">1.000000</td>
<td align="center">3</td>
</tr>
<tr class="odd">
<td align="center">{e}</td>
<td align="center">{f}</td>
<td align="center">0.6</td>
<td align="center">1.00</td>
<td align="center">0.6</td>
<td align="center">1.666667</td>
<td align="center">3</td>
</tr>
<tr class="even">
<td align="center">{f}</td>
<td align="center">{e}</td>
<td align="center">0.6</td>
<td align="center">1.00</td>
<td align="center">0.6</td>
<td align="center">1.666667</td>
<td align="center">3</td>
</tr>
<tr class="odd">
<td align="center">{e}</td>
<td align="center">{b}</td>
<td align="center">0.6</td>
<td align="center">1.00</td>
<td align="center">0.6</td>
<td align="center">1.000000</td>
<td align="center">3</td>
</tr>
<tr class="even">
<td align="center">{f}</td>
<td align="center">{b}</td>
<td align="center">0.6</td>
<td align="center">1.00</td>
<td align="center">0.6</td>
<td align="center">1.000000</td>
<td align="center">3</td>
</tr>
<tr class="odd">
<td align="center">{c}</td>
<td align="center">{b}</td>
<td align="center">0.8</td>
<td align="center">1.00</td>
<td align="center">0.8</td>
<td align="center">1.000000</td>
<td align="center">4</td>
</tr>
<tr class="even">
<td align="center">{b}</td>
<td align="center">{c}</td>
<td align="center">0.8</td>
<td align="center">0.80</td>
<td align="center">1.0</td>
<td align="center">1.000000</td>
<td align="center">4</td>
</tr>
<tr class="odd">
<td align="center">{c, g}</td>
<td align="center">{b}</td>
<td align="center">0.6</td>
<td align="center">1.00</td>
<td align="center">0.6</td>
<td align="center">1.000000</td>
<td align="center">3</td>
</tr>
<tr class="even">
<td align="center">{b, g}</td>
<td align="center">{c}</td>
<td align="center">0.6</td>
<td align="center">1.00</td>
<td align="center">0.6</td>
<td align="center">1.250000</td>
<td align="center">3</td>
</tr>
<tr class="odd">
<td align="center">{b, c}</td>
<td align="center">{g}</td>
<td align="center">0.6</td>
<td align="center">0.75</td>
<td align="center">0.8</td>
<td align="center">1.250000</td>
<td align="center">3</td>
</tr>
<tr class="even">
<td align="center">{c, e}</td>
<td align="center">{f}</td>
<td align="center">0.4</td>
<td align="center">1.00</td>
<td align="center">0.4</td>
<td align="center">1.666667</td>
<td align="center">2</td>
</tr>
<tr class="odd">
<td align="center">{c, f}</td>
<td align="center">{e}</td>
<td align="center">0.4</td>
<td align="center">1.00</td>
<td align="center">0.4</td>
<td align="center">1.666667</td>
<td align="center">2</td>
</tr>
<tr class="even">
<td align="center">{e, f}</td>
<td align="center">{b}</td>
<td align="center">0.6</td>
<td align="center">1.00</td>
<td align="center">0.6</td>
<td align="center">1.000000</td>
<td align="center">3</td>
</tr>
<tr class="odd">
<td align="center">{b, e}</td>
<td align="center">{f}</td>
<td align="center">0.6</td>
<td align="center">1.00</td>
<td align="center">0.6</td>
<td align="center">1.666667</td>
<td align="center">3</td>
</tr>
<tr class="even">
<td align="center">{b, f}</td>
<td align="center">{e}</td>
<td align="center">0.6</td>
<td align="center">1.00</td>
<td align="center">0.6</td>
<td align="center">1.666667</td>
<td align="center">3</td>
</tr>
<tr class="odd">
<td align="center">{c, e}</td>
<td align="center">{b}</td>
<td align="center">0.4</td>
<td align="center">1.00</td>
<td align="center">0.4</td>
<td align="center">1.000000</td>
<td align="center">2</td>
</tr>
<tr class="even">
<td align="center">{c, f}</td>
<td align="center">{b}</td>
<td align="center">0.4</td>
<td align="center">1.00</td>
<td align="center">0.4</td>
<td align="center">1.000000</td>
<td align="center">2</td>
</tr>
<tr class="odd">
<td align="center">{c, e, f}</td>
<td align="center">{b}</td>
<td align="center">0.4</td>
<td align="center">1.00</td>
<td align="center">0.4</td>
<td align="center">1.000000</td>
<td align="center">2</td>
</tr>
<tr class="even">
<td align="center">{b, c, e}</td>
<td align="center">{f}</td>
<td align="center">0.4</td>
<td align="center">1.00</td>
<td align="center">0.4</td>
<td align="center">1.666667</td>
<td align="center">2</td>
</tr>
<tr class="odd">
<td align="center">{b, c, f}</td>
<td align="center">{e}</td>
<td align="center">0.4</td>
<td align="center">1.00</td>
<td align="center">0.4</td>
<td align="center">1.666667</td>
<td align="center">2</td>
</tr>
</tbody>
</table>
<p>위 Table <a href="association-rule.html#tab:apriori-r-results">15.3</a>를 살펴보면, 결과부에는 오직 하나의 항목만 존재하는 것을 알 수 있다. 이는 Apriori 알고리즘이 제안된 원 논문 <span class="citation">(Agrawal, Imieliński, and Swami <a href="#ref-agrawal1993mining" role="doc-biblioref">1993</a>)</span>에 따른 것이며, 위 <a href="association-rule.html#apriori-rule-exploration">15.3.2</a> 절에서 여러 개의 항목이 결과부에 존재하는 방식은 이 Apriori 알고리즘을 보다 일반화한 것이라 생각할 수 있겠다.</p>
</div>
</div>
<div id="association-sequential-pattern" class="section level2">
<h2><span class="header-section-number">15.4</span> 순차적 패턴의 탐사</h2>
<p>순차적 패턴(sequential pattern)이란 고객들의 시간에 따른 구매 행태를 말하는데, 예를 들어 “냉장고를 구입한 후 김치냉장고를 구매한다”는 식이다.</p>
<p>순차적 패턴의 탐사를 위해서는 고객별, 시간별 트랜잭션 데이터가 필요하다. 항목 집합을 순서적으로 나열한 리스트를 시퀀스(sequence)라 하는데, <span class="math inline">\(A_j\)</span>를 <span class="math inline">\(j\)</span>번째의 항목집합이라 할 때, 시퀀스는 다음과 같이 표기한다.</p>
<p><span class="math display">\[\begin{equation*}
s = &lt; A_1, A_2, \cdots, A_n &gt;
\end{equation*}\]</span></p>
<p>시퀀스에 포함된 항목집합의 수를 시퀀스의 길이라 하며, 길이가 <span class="math inline">\(k\)</span>인 시퀀스를 <span class="math inline">\(k\)</span>-시퀀스라 한다.</p>
<p><span class="math display">\[\begin{equation*}
length(&lt; A_1, A_2, \cdots, A_n &gt;) = n
\end{equation*}\]</span></p>
<p>두 시퀀스 <span class="math inline">\(s_1 = &lt; A_1, A_2, \cdots, A_n &gt;\)</span>과 <span class="math inline">\(s_2 = &lt; B_1, B_2, \cdots, B_m &gt;\)</span>에 대하여 (<span class="math inline">\(n \leq m\)</span>),</p>
<p><span class="math display">\[\begin{equation*}
A_1 \subseteq B_{i_1}, A_2 \subseteq B_{i_2}, \cdots,  A_n \subseteq B_{i_n}
\end{equation*}\]</span></p>
<p>이 성립하는 <span class="math inline">\(i_1 &lt; i_2 &lt; \cdots &lt; i_n\)</span>이 존재할 때, <span class="math inline">\(s_1\)</span>은 <span class="math inline">\(s_2\)</span>에 포함된다고 하며, 이 때 <span class="math inline">\(s_1\)</span>을 <span class="math inline">\(s_2\)</span>의 부분 시퀀스라 하며, 아래와 같이 표현한다.</p>
<p><span class="math display">\[\begin{equation*}
s_1 \prec s_2
\end{equation*}\]</span></p>
<p>시퀀스 <span class="math inline">\(s\)</span>가 어떤 다른 시퀀스에 포함되지 않을 경우 최대 시퀀스(maximal sequence)라 한다.</p>
<p><span class="math inline">\(N\)</span>명의 고객 각자에 대한 트랜잭션 시퀀스를 고객 시퀀스(customer sequence)라 하며, <span class="math inline">\(i\)</span>번째 고객에 대한 고객 시퀀스를 <span class="math inline">\(s_i\)</span>라 할 때 (<span class="math inline">\(i = 1, \cdots, N\)</span>), 임의의 시퀀스 <span class="math inline">\(s\)</span>에 대한 지지도를 다음과 같이 정의한다.</p>
<p><span class="math display">\[\begin{equation*}
supp(s) = \frac{1}{N} \sum_{i = 1}^{N} I(s \prec s_i)
\end{equation*}\]</span></p>
<p>그리고, 미리 정한 최소 지지도 이상을 갖는 시퀀스를 빈발 시퀀스(large sequence)라 한다. 따라서, 순차적 패턴 탐사 문제는 빈발 시퀀스 중 최대 시퀀스(maximal sequence)들을 찾는 것이라 할 수 있다.</p>
<div id="association-aprioriall" class="section level3">
<h3><span class="header-section-number">15.4.1</span> AprioriAll 알고리즘</h3>
<p>AprioriAll 알고리즘은 빈발 시퀀스를 탐색하나, 탐색된 시퀀스가 최대 빈발 시퀀스임을 보장하지는 못한다. 따라서, 후에 최대화 단계를 요한다.</p>
<p>아래와 같은 고객 시퀀스가 존재한다고 하자.</p>
<div class="sourceCode" id="cb671"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb671-1"><a href="association-rule.html#cb671-1"></a>sequential_transaction_df &lt;-<span class="st"> </span><span class="kw">tribble</span>(</span>
<span id="cb671-2"><a href="association-rule.html#cb671-2"></a>  <span class="op">~</span>customer_id, <span class="op">~</span>transaction_seq, <span class="op">~</span>item,</span>
<span id="cb671-3"><a href="association-rule.html#cb671-3"></a>  <span class="dv">1</span>, <span class="dv">1</span>, <span class="st">&quot;a&quot;</span>,</span>
<span id="cb671-4"><a href="association-rule.html#cb671-4"></a>  <span class="dv">1</span>, <span class="dv">2</span>, <span class="st">&quot;b&quot;</span>,</span>
<span id="cb671-5"><a href="association-rule.html#cb671-5"></a>  <span class="dv">2</span>, <span class="dv">1</span>, <span class="st">&quot;c&quot;</span>,</span>
<span id="cb671-6"><a href="association-rule.html#cb671-6"></a>  <span class="dv">2</span>, <span class="dv">1</span>, <span class="st">&quot;d&quot;</span>,</span>
<span id="cb671-7"><a href="association-rule.html#cb671-7"></a>  <span class="dv">2</span>, <span class="dv">2</span>, <span class="st">&quot;a&quot;</span>,</span>
<span id="cb671-8"><a href="association-rule.html#cb671-8"></a>  <span class="dv">2</span>, <span class="dv">3</span>, <span class="st">&quot;e&quot;</span>,</span>
<span id="cb671-9"><a href="association-rule.html#cb671-9"></a>  <span class="dv">2</span>, <span class="dv">3</span>, <span class="st">&quot;f&quot;</span>,</span>
<span id="cb671-10"><a href="association-rule.html#cb671-10"></a>  <span class="dv">2</span>, <span class="dv">3</span>, <span class="st">&quot;g&quot;</span>,</span>
<span id="cb671-11"><a href="association-rule.html#cb671-11"></a>  <span class="dv">3</span>, <span class="dv">1</span>, <span class="st">&quot;a&quot;</span>,</span>
<span id="cb671-12"><a href="association-rule.html#cb671-12"></a>  <span class="dv">3</span>, <span class="dv">1</span>, <span class="st">&quot;h&quot;</span>,</span>
<span id="cb671-13"><a href="association-rule.html#cb671-13"></a>  <span class="dv">3</span>, <span class="dv">1</span>, <span class="st">&quot;g&quot;</span>,</span>
<span id="cb671-14"><a href="association-rule.html#cb671-14"></a>  <span class="dv">4</span>, <span class="dv">1</span>, <span class="st">&quot;a&quot;</span>,</span>
<span id="cb671-15"><a href="association-rule.html#cb671-15"></a>  <span class="dv">4</span>, <span class="dv">2</span>, <span class="st">&quot;e&quot;</span>,</span>
<span id="cb671-16"><a href="association-rule.html#cb671-16"></a>  <span class="dv">4</span>, <span class="dv">2</span>, <span class="st">&quot;g&quot;</span>,</span>
<span id="cb671-17"><a href="association-rule.html#cb671-17"></a>  <span class="dv">4</span>, <span class="dv">3</span>, <span class="st">&quot;b&quot;</span>,</span>
<span id="cb671-18"><a href="association-rule.html#cb671-18"></a>  <span class="dv">5</span>, <span class="dv">1</span>, <span class="st">&quot;b&quot;</span></span>
<span id="cb671-19"><a href="association-rule.html#cb671-19"></a>)</span>
<span id="cb671-20"><a href="association-rule.html#cb671-20"></a></span>
<span id="cb671-21"><a href="association-rule.html#cb671-21"></a>sequential_transaction_df <span class="op">%&gt;%</span></span>
<span id="cb671-22"><a href="association-rule.html#cb671-22"></a><span class="st">  </span><span class="kw">group_by</span>(customer_id, transaction_seq) <span class="op">%&gt;%</span></span>
<span id="cb671-23"><a href="association-rule.html#cb671-23"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">itemset =</span> <span class="kw">str_c</span>(<span class="st">&quot;{&quot;</span>, <span class="kw">str_c</span>(item, <span class="dt">collapse =</span> <span class="st">&quot;, &quot;</span>), <span class="st">&quot;}&quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb671-24"><a href="association-rule.html#cb671-24"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">sequence =</span> <span class="kw">str_c</span>(<span class="st">&quot;&lt;&quot;</span>, <span class="kw">str_c</span>(itemset, <span class="dt">collapse =</span> <span class="st">&quot;, &quot;</span>), <span class="st">&quot;&gt;&quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb671-25"><a href="association-rule.html#cb671-25"></a><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>(</span>
<span id="cb671-26"><a href="association-rule.html#cb671-26"></a>    <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</span>
<span id="cb671-27"><a href="association-rule.html#cb671-27"></a>    <span class="dt">align =</span> <span class="kw">c</span>(<span class="st">&quot;c&quot;</span>, <span class="st">&quot;c&quot;</span>),</span>
<span id="cb671-28"><a href="association-rule.html#cb671-28"></a>    <span class="dt">col.names =</span> <span class="kw">c</span>(<span class="st">&quot;고객ID ($i$)&quot;</span>, <span class="st">&quot;고객 시퀀스 ($s_i$)&quot;</span>),</span>
<span id="cb671-29"><a href="association-rule.html#cb671-29"></a>    <span class="dt">caption =</span> <span class="st">&quot;고객별 시퀀스&quot;</span></span>
<span id="cb671-30"><a href="association-rule.html#cb671-30"></a>  )</span></code></pre></div>
<pre><code>## `summarise()` regrouping output by &#39;customer_id&#39; (override with `.groups` argument)</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<table>
<caption><span id="tab:sequential-transaction-data">Table 15.4: </span>고객별 시퀀스</caption>
<thead>
<tr class="header">
<th align="center">고객ID (<span class="math inline">\(i\)</span>)</th>
<th align="center">고객 시퀀스 (<span class="math inline">\(s_i\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">&lt;{a}, {b}&gt;</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">&lt;{c, d}, {a}, {e, f, g}&gt;</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">&lt;{a, h, g}&gt;</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">&lt;{a}, {e, g}, {b}&gt;</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">&lt;{b}&gt;</td>
</tr>
</tbody>
</table>
<p>고객 시퀀스의 항목집합 또는 이의 부분집합 중 최소 지지도 이상인 것들을 빈발항목 집합으로 도출한다.</p>
<p>우선 시퀀스가 특정 패턴을 포함하는지 여부를 판단하는 사용자 정의 함수 <code>is_contained</code>와 고객 시퀀스 집합의 특정 패턴에 대한 지지도를 산출하는 사용자 정의 함수 <code>support_sequence</code>를 아래와 같이 구현해보자.</p>
<div class="sourceCode" id="cb674"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb674-1"><a href="association-rule.html#cb674-1"></a>is_contained &lt;-<span class="st"> </span><span class="cf">function</span>(x, pattern) {</span>
<span id="cb674-2"><a href="association-rule.html#cb674-2"></a>  n_x &lt;-<span class="st"> </span><span class="kw">length</span>(x)</span>
<span id="cb674-3"><a href="association-rule.html#cb674-3"></a>  n_pattern &lt;-<span class="st"> </span><span class="kw">length</span>(pattern)</span>
<span id="cb674-4"><a href="association-rule.html#cb674-4"></a>  <span class="cf">if</span> (n_pattern <span class="op">==</span><span class="st"> </span><span class="dv">0</span>) <span class="kw">return</span> (<span class="ot">TRUE</span>)</span>
<span id="cb674-5"><a href="association-rule.html#cb674-5"></a>  </span>
<span id="cb674-6"><a href="association-rule.html#cb674-6"></a>  rtn &lt;-<span class="st"> </span><span class="ot">FALSE</span></span>
<span id="cb674-7"><a href="association-rule.html#cb674-7"></a>  </span>
<span id="cb674-8"><a href="association-rule.html#cb674-8"></a>  location &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="ot">NA_integer_</span>, n_pattern)</span>
<span id="cb674-9"><a href="association-rule.html#cb674-9"></a></span>
<span id="cb674-10"><a href="association-rule.html#cb674-10"></a>  <span class="cf">if</span> (n_x <span class="op">&gt;=</span><span class="st"> </span>n_pattern) {</span>
<span id="cb674-11"><a href="association-rule.html#cb674-11"></a>    j &lt;-<span class="st"> </span>1L</span>
<span id="cb674-12"><a href="association-rule.html#cb674-12"></a>    <span class="cf">for</span>(i <span class="cf">in</span> <span class="kw">seq_len</span>(n_x)) {</span>
<span id="cb674-13"><a href="association-rule.html#cb674-13"></a>      <span class="cf">if</span> (<span class="kw">is_empty</span>(<span class="kw">setdiff</span>(pattern[[j]], x[[i]]))) {</span>
<span id="cb674-14"><a href="association-rule.html#cb674-14"></a>        location[j] &lt;-<span class="st"> </span>i</span>
<span id="cb674-15"><a href="association-rule.html#cb674-15"></a>        j &lt;-<span class="st"> </span>j <span class="op">+</span><span class="st"> </span><span class="dv">1</span></span>
<span id="cb674-16"><a href="association-rule.html#cb674-16"></a>        <span class="cf">if</span> (j <span class="op">&gt;</span><span class="st"> </span>n_pattern) {</span>
<span id="cb674-17"><a href="association-rule.html#cb674-17"></a>          rtn &lt;-<span class="st"> </span><span class="ot">TRUE</span></span>
<span id="cb674-18"><a href="association-rule.html#cb674-18"></a>          <span class="cf">break</span></span>
<span id="cb674-19"><a href="association-rule.html#cb674-19"></a>        }</span>
<span id="cb674-20"><a href="association-rule.html#cb674-20"></a>      }</span>
<span id="cb674-21"><a href="association-rule.html#cb674-21"></a>    }</span>
<span id="cb674-22"><a href="association-rule.html#cb674-22"></a>  }</span>
<span id="cb674-23"><a href="association-rule.html#cb674-23"></a></span>
<span id="cb674-24"><a href="association-rule.html#cb674-24"></a>  rtn</span>
<span id="cb674-25"><a href="association-rule.html#cb674-25"></a>}</span>
<span id="cb674-26"><a href="association-rule.html#cb674-26"></a></span>
<span id="cb674-27"><a href="association-rule.html#cb674-27"></a>support_sequence &lt;-<span class="st"> </span><span class="cf">function</span>(sequence_list, pattern) {</span>
<span id="cb674-28"><a href="association-rule.html#cb674-28"></a>  <span class="kw">map_lgl</span>(sequence_list, is_contained, <span class="dt">pattern =</span> pattern) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()</span>
<span id="cb674-29"><a href="association-rule.html#cb674-29"></a>}</span></code></pre></div>
<p>앞 <a href="association-rule.html#apriori-large-itemsets">15.3.1</a>절에서와 같이 사용자 정의 함수 <code>apriori_gen</code>을 이용하여 빈발항목집합(시퀀스 지지도 기준)을 아래와 같이 얻는다.</p>
<div class="sourceCode" id="cb675"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb675-1"><a href="association-rule.html#cb675-1"></a>s_min &lt;-<span class="st"> </span><span class="fl">0.4</span></span>
<span id="cb675-2"><a href="association-rule.html#cb675-2"></a></span>
<span id="cb675-3"><a href="association-rule.html#cb675-3"></a>customer_sequence &lt;-<span class="st"> </span>sequential_transaction_df <span class="op">%&gt;%</span></span>
<span id="cb675-4"><a href="association-rule.html#cb675-4"></a><span class="st">  </span><span class="kw">group_by</span>(customer_id, transaction_seq) <span class="op">%&gt;%</span></span>
<span id="cb675-5"><a href="association-rule.html#cb675-5"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">itemset =</span> <span class="kw">list</span>(item)) <span class="op">%&gt;%</span></span>
<span id="cb675-6"><a href="association-rule.html#cb675-6"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">sequence =</span> <span class="kw">list</span>(itemset))</span></code></pre></div>
<pre><code>## `summarise()` regrouping output by &#39;customer_id&#39; (override with `.groups` argument)</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb678"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb678-1"><a href="association-rule.html#cb678-1"></a>candidate_itemsets &lt;-<span class="st"> </span><span class="kw">map</span>(<span class="kw">sort</span>(<span class="kw">unique</span>(sequential_transaction_df<span class="op">$</span>item)), <span class="op">~</span><span class="kw">list</span>(.x))</span>
<span id="cb678-2"><a href="association-rule.html#cb678-2"></a>large_itemsets &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&quot;list&quot;</span>, <span class="dt">length =</span> <span class="kw">length</span>(candidate_itemsets))</span>
<span id="cb678-3"><a href="association-rule.html#cb678-3"></a></span>
<span id="cb678-4"><a href="association-rule.html#cb678-4"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">seq_along</span>(large_itemsets)) {</span>
<span id="cb678-5"><a href="association-rule.html#cb678-5"></a>  large_itemsets[[i]] &lt;-<span class="st"> </span>candidate_itemsets[</span>
<span id="cb678-6"><a href="association-rule.html#cb678-6"></a>    <span class="kw">map_dbl</span>(candidate_itemsets,</span>
<span id="cb678-7"><a href="association-rule.html#cb678-7"></a>            <span class="op">~</span><span class="kw">support_sequence</span>(customer_sequence<span class="op">$</span>sequence, <span class="dt">pattern =</span> .x)) <span class="op">&gt;=</span><span class="st"> </span>s_min</span>
<span id="cb678-8"><a href="association-rule.html#cb678-8"></a>    ] <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">flatten</span>()</span>
<span id="cb678-9"><a href="association-rule.html#cb678-9"></a></span>
<span id="cb678-10"><a href="association-rule.html#cb678-10"></a>  candidate_itemsets &lt;-<span class="st"> </span><span class="kw">map</span>(<span class="kw">apriori_gen</span>(large_itemsets[[i]]), <span class="op">~</span><span class="kw">list</span>(.x))</span>
<span id="cb678-11"><a href="association-rule.html#cb678-11"></a>}</span>
<span id="cb678-12"><a href="association-rule.html#cb678-12"></a></span>
<span id="cb678-13"><a href="association-rule.html#cb678-13"></a>large_itemsets &lt;-<span class="st"> </span>large_itemsets <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">flatten</span>()</span></code></pre></div>
<p>위 결과, 아래와 같은 빈발항목집합이 얻어진다.</p>
<div class="sourceCode" id="cb679"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb679-1"><a href="association-rule.html#cb679-1"></a>large_itemsets</span></code></pre></div>
<pre><code>## [[1]]
## [1] &quot;a&quot;
## 
## [[2]]
## [1] &quot;b&quot;
## 
## [[3]]
## [1] &quot;e&quot;
## 
## [[4]]
## [1] &quot;g&quot;
## 
## [[5]]
## [1] &quot;e&quot; &quot;g&quot;</code></pre>
<p>위 빈발항목집합에 일련번호를 부여한 뒤, 고객 시퀀스를 해당 일련번호를 이용한 시퀀스로 변환한다. 우선 아래와 같이 일련번호를 부여해보자.</p>
<div class="sourceCode" id="cb681"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb681-1"><a href="association-rule.html#cb681-1"></a>large_itemset_df &lt;-<span class="st"> </span><span class="kw">tibble</span>(</span>
<span id="cb681-2"><a href="association-rule.html#cb681-2"></a>  <span class="dt">itemset =</span> large_itemsets,</span>
<span id="cb681-3"><a href="association-rule.html#cb681-3"></a>  <span class="dt">mapped_to =</span> <span class="kw">seq_along</span>(large_itemsets)</span>
<span id="cb681-4"><a href="association-rule.html#cb681-4"></a>)</span>
<span id="cb681-5"><a href="association-rule.html#cb681-5"></a></span>
<span id="cb681-6"><a href="association-rule.html#cb681-6"></a>large_itemset_df <span class="op">%&gt;%</span></span>
<span id="cb681-7"><a href="association-rule.html#cb681-7"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span></span>
<span id="cb681-8"><a href="association-rule.html#cb681-8"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">itemset =</span> <span class="kw">str_c</span>(<span class="st">&quot;{&quot;</span>, <span class="kw">str_c</span>(itemset, <span class="dt">collapse =</span> <span class="st">&quot;, &quot;</span>), <span class="st">&quot;}&quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb681-9"><a href="association-rule.html#cb681-9"></a><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>(</span>
<span id="cb681-10"><a href="association-rule.html#cb681-10"></a>    <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</span>
<span id="cb681-11"><a href="association-rule.html#cb681-11"></a>    <span class="dt">align =</span> <span class="kw">c</span>(<span class="st">&quot;c&quot;</span>, <span class="st">&quot;c&quot;</span>),</span>
<span id="cb681-12"><a href="association-rule.html#cb681-12"></a>    <span class="dt">col.names =</span> <span class="kw">c</span>(<span class="st">&quot;빈발항목집합&quot;</span>, <span class="st">&quot;일련번호&quot;</span>),</span>
<span id="cb681-13"><a href="association-rule.html#cb681-13"></a>    <span class="dt">caption =</span> <span class="st">&quot;고객 시퀀스 빈발항목집합&quot;</span></span>
<span id="cb681-14"><a href="association-rule.html#cb681-14"></a>  )</span></code></pre></div>
<table>
<caption><span id="tab:association-sequence-large-itemsets">Table 15.5: </span>고객 시퀀스 빈발항목집합</caption>
<thead>
<tr class="header">
<th align="center">빈발항목집합</th>
<th align="center">일련번호</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">{a}</td>
<td align="center">1</td>
</tr>
<tr class="even">
<td align="center">{b}</td>
<td align="center">2</td>
</tr>
<tr class="odd">
<td align="center">{e}</td>
<td align="center">3</td>
</tr>
<tr class="even">
<td align="center">{g}</td>
<td align="center">4</td>
</tr>
<tr class="odd">
<td align="center">{e, g}</td>
<td align="center">5</td>
</tr>
</tbody>
</table>
<p>원 고객 시퀀스에 대해, 각 항목집합이 위 빈발항목집합을 포함하는 경우, 해당 일련번호가 항목으로 포함되는 형태로 변환 시퀀스를 생성한다.</p>
<div class="sourceCode" id="cb682"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb682-1"><a href="association-rule.html#cb682-1"></a>customer_sequence<span class="op">$</span>transformed_sequence &lt;-<span class="st"> </span>customer_sequence<span class="op">$</span>sequence <span class="op">%&gt;%</span></span>
<span id="cb682-2"><a href="association-rule.html#cb682-2"></a><span class="st">  </span><span class="kw">map</span>(<span class="op">~</span><span class="kw">map</span>(.x, <span class="cf">function</span>(x) {</span>
<span id="cb682-3"><a href="association-rule.html#cb682-3"></a>    large_itemset_df<span class="op">$</span>mapped_to[</span>
<span id="cb682-4"><a href="association-rule.html#cb682-4"></a>      <span class="kw">map_lgl</span>(large_itemset_df<span class="op">$</span>itemset, <span class="op">~</span><span class="kw">is_contained</span>(x, .x))</span>
<span id="cb682-5"><a href="association-rule.html#cb682-5"></a>      ]</span>
<span id="cb682-6"><a href="association-rule.html#cb682-6"></a>  }) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">compact</span>())</span></code></pre></div>
<p>원 고객 시퀀스와 변환 시퀀스는 아래와 같이 표현될 수 있다.</p>
<div class="sourceCode" id="cb683"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb683-1"><a href="association-rule.html#cb683-1"></a>print_sequence &lt;-<span class="st"> </span><span class="cf">function</span>(sequence) {</span>
<span id="cb683-2"><a href="association-rule.html#cb683-2"></a>  <span class="kw">str_c</span>(<span class="st">&quot;&lt;&quot;</span>, <span class="kw">str_c</span>(</span>
<span id="cb683-3"><a href="association-rule.html#cb683-3"></a>    <span class="kw">map</span>(sequence, <span class="cf">function</span>(x) </span>
<span id="cb683-4"><a href="association-rule.html#cb683-4"></a>      <span class="kw">str_c</span>(<span class="kw">map_chr</span>(x, <span class="op">~</span><span class="kw">str_c</span>(<span class="st">&quot;{&quot;</span>, <span class="kw">str_c</span>(.x, <span class="dt">collapse =</span> <span class="st">&quot;, &quot;</span>), <span class="st">&quot;}&quot;</span>)), </span>
<span id="cb683-5"><a href="association-rule.html#cb683-5"></a>            <span class="dt">collapse =</span> <span class="st">&quot;, &quot;</span>)),</span>
<span id="cb683-6"><a href="association-rule.html#cb683-6"></a>    <span class="st">&quot;&gt;&quot;</span>))</span>
<span id="cb683-7"><a href="association-rule.html#cb683-7"></a>}</span>
<span id="cb683-8"><a href="association-rule.html#cb683-8"></a></span>
<span id="cb683-9"><a href="association-rule.html#cb683-9"></a>customer_sequence <span class="op">%&gt;%</span></span>
<span id="cb683-10"><a href="association-rule.html#cb683-10"></a><span class="st">  </span><span class="kw">group_by</span>(customer_id) <span class="op">%&gt;%</span></span>
<span id="cb683-11"><a href="association-rule.html#cb683-11"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb683-12"><a href="association-rule.html#cb683-12"></a>    <span class="dt">sequence =</span> <span class="kw">print_sequence</span>(sequence),</span>
<span id="cb683-13"><a href="association-rule.html#cb683-13"></a>    <span class="dt">transformed_sequence =</span> <span class="kw">print_sequence</span>(transformed_sequence)</span>
<span id="cb683-14"><a href="association-rule.html#cb683-14"></a>  ) <span class="op">%&gt;%</span></span>
<span id="cb683-15"><a href="association-rule.html#cb683-15"></a><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>(</span>
<span id="cb683-16"><a href="association-rule.html#cb683-16"></a>    <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</span>
<span id="cb683-17"><a href="association-rule.html#cb683-17"></a>    <span class="dt">align =</span> <span class="kw">c</span>(<span class="st">&quot;c&quot;</span>, <span class="st">&quot;c&quot;</span>, <span class="st">&quot;c&quot;</span>),</span>
<span id="cb683-18"><a href="association-rule.html#cb683-18"></a>    <span class="dt">col.names =</span> <span class="kw">c</span>(<span class="st">&quot;고객ID&quot;</span>, <span class="st">&quot;고객 시퀀스&quot;</span>, <span class="st">&quot;변환 시퀀스&quot;</span>),</span>
<span id="cb683-19"><a href="association-rule.html#cb683-19"></a>    <span class="dt">caption =</span> <span class="st">&quot;고객 시퀀스의 변환&quot;</span></span>
<span id="cb683-20"><a href="association-rule.html#cb683-20"></a>  )</span></code></pre></div>
<table>
<caption><span id="tab:association-transformed-sequence">Table 15.6: </span>고객 시퀀스의 변환</caption>
<thead>
<tr class="header">
<th align="center">고객ID</th>
<th align="center">고객 시퀀스</th>
<th align="center">변환 시퀀스</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">&lt;{a}, {b}&gt;</td>
<td align="center">&lt;{1}, {2}&gt;</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">&lt;{c, d}, {a}, {e, f, g}&gt;</td>
<td align="center">&lt;{1}, {3, 4, 5}&gt;</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">&lt;{a, h, g}&gt;</td>
<td align="center">&lt;{1, 4}&gt;</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">&lt;{a}, {e, g}, {b}&gt;</td>
<td align="center">&lt;{1}, {3, 4, 5}, {2}&gt;</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">&lt;{b}&gt;</td>
<td align="center">&lt;{2}&gt;</td>
</tr>
</tbody>
</table>
<p>변환 시퀀스를 기준으로, 길이가 1인 빈발 시퀀스를 구한다. 최소 지지도를 앞에서 빈발항목집합을 구할 때와 동일하게 설정할 때, 길이가 1인 빈발 시퀀스는 빈발항목집합(의 변환된 일련번호)과 동일하다.</p>
<p>우선, 최대 시퀀스 길이를 구하자.</p>
<div class="sourceCode" id="cb684"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb684-1"><a href="association-rule.html#cb684-1"></a>max_sequence_length &lt;-<span class="st"> </span><span class="kw">max</span>(<span class="kw">map_int</span>(customer_sequence<span class="op">$</span>transformed_sequence, <span class="op">~</span><span class="kw">length</span>(.x)))</span></code></pre></div>
<p>1-시퀀스인 빈발시퀀스는 빈발항목집합과 같다.</p>
<div class="sourceCode" id="cb685"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb685-1"><a href="association-rule.html#cb685-1"></a>large_sequences &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&quot;list&quot;</span>, <span class="dt">length =</span> max_sequence_length)</span>
<span id="cb685-2"><a href="association-rule.html#cb685-2"></a>large_sequences[[<span class="dv">1</span>]] &lt;-<span class="st"> </span><span class="kw">map</span>(large_itemset_df<span class="op">$</span>mapped_to, <span class="op">~</span><span class="kw">list</span>(.x))</span></code></pre></div>
<p>같은 길이의 두 시퀀스를 이용해서 길이가 1 증가한 새로운 시퀀스를 생성하는 함수 <code>generate_sequence</code>를 아래와 같이 구현해보자. 새로운 시퀀스는 첫 번째 시퀀스 후에 두 번째 시퀀스의 가장 마지막 트랜잭션을 추가한 시퀀스이다.</p>
<div class="sourceCode" id="cb686"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb686-1"><a href="association-rule.html#cb686-1"></a>generate_sequence &lt;-<span class="st"> </span><span class="cf">function</span>(seq1, seq2) {</span>
<span id="cb686-2"><a href="association-rule.html#cb686-2"></a>  <span class="cf">if</span> (<span class="kw">length</span>(seq1) <span class="op">!=</span><span class="st"> </span><span class="kw">length</span>(seq2)) <span class="kw">stop</span>(<span class="st">&quot;Two sequences must be the same length.&quot;</span>)</span>
<span id="cb686-3"><a href="association-rule.html#cb686-3"></a>  </span>
<span id="cb686-4"><a href="association-rule.html#cb686-4"></a>  <span class="co"># two k-sequences needs to be the same for first k-1 items to generate new sequence</span></span>
<span id="cb686-5"><a href="association-rule.html#cb686-5"></a>  new_sequence &lt;-<span class="st"> </span><span class="ot">NULL</span></span>
<span id="cb686-6"><a href="association-rule.html#cb686-6"></a>  k &lt;-<span class="st"> </span><span class="kw">length</span>(seq1)</span>
<span id="cb686-7"><a href="association-rule.html#cb686-7"></a>  <span class="cf">if</span> (<span class="kw">identical</span>(seq1[<span class="kw">seq_len</span>(k <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)], seq2[<span class="kw">seq_len</span>(k <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)])) {</span>
<span id="cb686-8"><a href="association-rule.html#cb686-8"></a>    new_sequence &lt;-<span class="st"> </span><span class="kw">c</span>(seq1, seq2[[k]])</span>
<span id="cb686-9"><a href="association-rule.html#cb686-9"></a>  }</span>
<span id="cb686-10"><a href="association-rule.html#cb686-10"></a>  </span>
<span id="cb686-11"><a href="association-rule.html#cb686-11"></a>  new_sequence</span>
<span id="cb686-12"><a href="association-rule.html#cb686-12"></a>}</span></code></pre></div>
<p>빈발 <span class="math inline">\(k\)</span>-시퀀스들로부터 <span class="math inline">\((k+1)\)</span>-시퀀스들을 생성하는 함수 <code>apriori_seq_gen</code>을 아래와 같이 구현해보자.</p>
<div class="sourceCode" id="cb687"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb687-1"><a href="association-rule.html#cb687-1"></a>apriori_seq_gen &lt;-<span class="st"> </span><span class="cf">function</span>(L) {</span>
<span id="cb687-2"><a href="association-rule.html#cb687-2"></a>  n_seqs &lt;-<span class="st"> </span><span class="kw">length</span>(L)</span>
<span id="cb687-3"><a href="association-rule.html#cb687-3"></a>  n_item &lt;-<span class="st"> </span><span class="kw">unique</span>(<span class="kw">map_dbl</span>(L, length))</span>
<span id="cb687-4"><a href="association-rule.html#cb687-4"></a>  </span>
<span id="cb687-5"><a href="association-rule.html#cb687-5"></a>  <span class="cf">if</span> (<span class="kw">length</span>(n_item) <span class="op">&gt;</span><span class="st"> </span><span class="dv">1</span>) <span class="kw">stop</span>(<span class="st">&quot;All sequences must be the same length.&quot;</span>)</span>
<span id="cb687-6"><a href="association-rule.html#cb687-6"></a>  </span>
<span id="cb687-7"><a href="association-rule.html#cb687-7"></a>  k &lt;-<span class="st"> </span>n_item</span>
<span id="cb687-8"><a href="association-rule.html#cb687-8"></a>  </span>
<span id="cb687-9"><a href="association-rule.html#cb687-9"></a>  <span class="co"># generate large new sequences with length (k+1)</span></span>
<span id="cb687-10"><a href="association-rule.html#cb687-10"></a>  C &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&quot;list&quot;</span>, <span class="dt">length =</span> n_seqs <span class="op">*</span><span class="st"> </span>n_seqs)</span>
<span id="cb687-11"><a href="association-rule.html#cb687-11"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">seq_along</span>(L)) {</span>
<span id="cb687-12"><a href="association-rule.html#cb687-12"></a>    <span class="cf">for</span> (j <span class="cf">in</span> <span class="kw">seq_along</span>(L)) {</span>
<span id="cb687-13"><a href="association-rule.html#cb687-13"></a>      candidate_sequence &lt;-<span class="st"> </span><span class="kw">generate_sequence</span>(L[[i]], L[[j]])</span>
<span id="cb687-14"><a href="association-rule.html#cb687-14"></a>      </span>
<span id="cb687-15"><a href="association-rule.html#cb687-15"></a>      <span class="co"># check whether all subsequences with length k are element of L</span></span>
<span id="cb687-16"><a href="association-rule.html#cb687-16"></a>      <span class="cf">if</span> (</span>
<span id="cb687-17"><a href="association-rule.html#cb687-17"></a>        <span class="kw">all</span>(<span class="kw">map_lgl</span>(<span class="kw">seq_len</span>(k), <span class="cf">function</span>(x) </span>
<span id="cb687-18"><a href="association-rule.html#cb687-18"></a>          <span class="kw">any</span>(<span class="kw">map_lgl</span>(L, <span class="op">~</span><span class="kw">identical</span>(.x, candidate_sequence[<span class="op">-</span>x])))</span>
<span id="cb687-19"><a href="association-rule.html#cb687-19"></a>        ))</span>
<span id="cb687-20"><a href="association-rule.html#cb687-20"></a>      ) {</span>
<span id="cb687-21"><a href="association-rule.html#cb687-21"></a>        C[[n_seqs <span class="op">*</span><span class="st"> </span>(i <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">+</span><span class="st"> </span>j]] &lt;-<span class="st"> </span>candidate_sequence</span>
<span id="cb687-22"><a href="association-rule.html#cb687-22"></a>      }</span>
<span id="cb687-23"><a href="association-rule.html#cb687-23"></a>    }</span>
<span id="cb687-24"><a href="association-rule.html#cb687-24"></a>  }</span>
<span id="cb687-25"><a href="association-rule.html#cb687-25"></a>  </span>
<span id="cb687-26"><a href="association-rule.html#cb687-26"></a>  <span class="kw">compact</span>(C)</span>
<span id="cb687-27"><a href="association-rule.html#cb687-27"></a>}</span></code></pre></div>
<p>위 <code>apriori_seq_gen</code> 함수 수행결과로 얻어지는 <span class="math inline">\((k+1)\)</span>-시퀀스들이 모두 빈발 시퀀스라는 보장은 없으므로, 새로 생성된 각 시퀀스가 최소 지지도 이상의 지지도를 갖는지 검토하여, 빈발 시퀀스만을 남기기로 하자. 앞에서 정의했던 함수 <code>support_sequence</code>를 활용하여, 새로운 함수 <code>get_large_sequence</code>를 정의하자.</p>
<div class="sourceCode" id="cb688"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb688-1"><a href="association-rule.html#cb688-1"></a>get_large_sequence &lt;-<span class="st"> </span><span class="cf">function</span>(sequence_list, C, s_min) {</span>
<span id="cb688-2"><a href="association-rule.html#cb688-2"></a>  is_large &lt;-<span class="st"> </span><span class="kw">map_lgl</span>(</span>
<span id="cb688-3"><a href="association-rule.html#cb688-3"></a>    C, <span class="op">~</span><span class="st"> </span><span class="kw">support_sequence</span>(sequence_list, .x) <span class="op">&gt;=</span><span class="st"> </span>s_min</span>
<span id="cb688-4"><a href="association-rule.html#cb688-4"></a>  )</span>
<span id="cb688-5"><a href="association-rule.html#cb688-5"></a>  </span>
<span id="cb688-6"><a href="association-rule.html#cb688-6"></a>  C[is_large]</span>
<span id="cb688-7"><a href="association-rule.html#cb688-7"></a>}</span></code></pre></div>
<p>위 빈발 <span class="math inline">\(k\)</span>-시퀀스를 과정을 <span class="math inline">\(k\)</span>값을 1씩 증가시켜가며 더 이상 빈발 시퀀스를 찾을 수 없을 때까지 반복한다.</p>
<div class="sourceCode" id="cb689"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb689-1"><a href="association-rule.html#cb689-1"></a>s_min &lt;-<span class="st"> </span><span class="fl">0.4</span></span>
<span id="cb689-2"><a href="association-rule.html#cb689-2"></a></span>
<span id="cb689-3"><a href="association-rule.html#cb689-3"></a>large_sequences &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&quot;list&quot;</span>, <span class="dt">length =</span> max_sequence_length)</span>
<span id="cb689-4"><a href="association-rule.html#cb689-4"></a>large_sequences[[<span class="dv">1</span>]] &lt;-<span class="st"> </span><span class="kw">map</span>(large_itemset_df<span class="op">$</span>mapped_to, <span class="op">~</span><span class="kw">list</span>(.x))</span>
<span id="cb689-5"><a href="association-rule.html#cb689-5"></a></span>
<span id="cb689-6"><a href="association-rule.html#cb689-6"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="kw">seq_len</span>(max_sequence_length <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)) {</span>
<span id="cb689-7"><a href="association-rule.html#cb689-7"></a>  large_sequences[[i <span class="op">+</span><span class="st"> </span><span class="dv">1</span>]] &lt;-<span class="st"> </span><span class="kw">get_large_sequence</span>(</span>
<span id="cb689-8"><a href="association-rule.html#cb689-8"></a>    customer_sequence<span class="op">$</span>transformed_sequence,</span>
<span id="cb689-9"><a href="association-rule.html#cb689-9"></a>    <span class="kw">apriori_seq_gen</span>(large_sequences[[i]]),</span>
<span id="cb689-10"><a href="association-rule.html#cb689-10"></a>    s_min</span>
<span id="cb689-11"><a href="association-rule.html#cb689-11"></a>  )</span>
<span id="cb689-12"><a href="association-rule.html#cb689-12"></a>  </span>
<span id="cb689-13"><a href="association-rule.html#cb689-13"></a>  <span class="cf">if</span>(<span class="kw">is_empty</span>(large_sequences[[i <span class="op">+</span><span class="st"> </span><span class="dv">1</span>]])) <span class="cf">break</span></span>
<span id="cb689-14"><a href="association-rule.html#cb689-14"></a>}</span>
<span id="cb689-15"><a href="association-rule.html#cb689-15"></a></span>
<span id="cb689-16"><a href="association-rule.html#cb689-16"></a>large_sequences &lt;-<span class="st"> </span><span class="kw">flatten</span>(<span class="kw">compact</span>(large_sequences))</span></code></pre></div>
<p>결과적으로 찾아진 빈발 시퀀스들은 아래와 같다.</p>
<div class="sourceCode" id="cb690"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb690-1"><a href="association-rule.html#cb690-1"></a><span class="kw">map_chr</span>(large_sequences, </span>
<span id="cb690-2"><a href="association-rule.html#cb690-2"></a>    <span class="op">~</span><span class="kw">str_c</span>(<span class="st">&quot;&lt;&quot;</span>, <span class="kw">str_c</span>(<span class="kw">str_c</span>(<span class="st">&quot;{&quot;</span>, <span class="kw">unlist</span>(.x), <span class="st">&quot;}&quot;</span>), <span class="dt">collapse =</span> <span class="st">&quot;, &quot;</span>), <span class="st">&quot;&gt;&quot;</span>))</span></code></pre></div>
<pre><code>## [1] &quot;&lt;{1}&gt;&quot;      &quot;&lt;{2}&gt;&quot;      &quot;&lt;{3}&gt;&quot;      &quot;&lt;{4}&gt;&quot;      &quot;&lt;{5}&gt;&quot;      &quot;&lt;{1}, {2}&gt;&quot;
## [7] &quot;&lt;{1}, {3}&gt;&quot; &quot;&lt;{1}, {4}&gt;&quot; &quot;&lt;{1}, {5}&gt;&quot;</code></pre>
<p>이후 최대화 단계를 통해, 빈발 시퀀스 중 최대 시퀀스들만 추출한다.</p>
<div class="sourceCode" id="cb692"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb692-1"><a href="association-rule.html#cb692-1"></a>maximal_large_sequences &lt;-<span class="st"> </span>large_sequences</span>
<span id="cb692-2"><a href="association-rule.html#cb692-2"></a></span>
<span id="cb692-3"><a href="association-rule.html#cb692-3"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">seq</span>(<span class="dt">from =</span> <span class="kw">length</span>(large_sequences), <span class="dt">to =</span> <span class="dv">2</span>)) {</span>
<span id="cb692-4"><a href="association-rule.html#cb692-4"></a>  <span class="cf">if</span>(<span class="op">!</span><span class="kw">is_empty</span>(maximal_large_sequences[i])) {</span>
<span id="cb692-5"><a href="association-rule.html#cb692-5"></a>    is_subsequence &lt;-<span class="st"> </span><span class="kw">map_lgl</span>(maximal_large_sequences[<span class="kw">seq_len</span>(i <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)],</span>
<span id="cb692-6"><a href="association-rule.html#cb692-6"></a>                              <span class="op">~</span><span class="kw">is_contained</span>(maximal_large_sequences[i], .x))</span>
<span id="cb692-7"><a href="association-rule.html#cb692-7"></a>    </span>
<span id="cb692-8"><a href="association-rule.html#cb692-8"></a>    <span class="kw">walk</span>(<span class="kw">which</span>(is_subsequence), <span class="cf">function</span>(x) maximal_large_sequences[[x]] &lt;&lt;-<span class="st"> </span><span class="kw">list</span>())</span>
<span id="cb692-9"><a href="association-rule.html#cb692-9"></a>  }</span>
<span id="cb692-10"><a href="association-rule.html#cb692-10"></a>}</span>
<span id="cb692-11"><a href="association-rule.html#cb692-11"></a></span>
<span id="cb692-12"><a href="association-rule.html#cb692-12"></a>maximal_large_sequences &lt;-<span class="st"> </span><span class="kw">compact</span>(maximal_large_sequences)</span></code></pre></div>
<p>최대 빈발 시퀀스(변환 시퀀스 기준)은 아래와 같다.</p>
<div class="sourceCode" id="cb693"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb693-1"><a href="association-rule.html#cb693-1"></a><span class="kw">map_chr</span>(maximal_large_sequences, </span>
<span id="cb693-2"><a href="association-rule.html#cb693-2"></a>    <span class="op">~</span><span class="kw">str_c</span>(<span class="st">&quot;&lt;&quot;</span>, <span class="kw">str_c</span>(<span class="kw">str_c</span>(<span class="st">&quot;{&quot;</span>, <span class="kw">unlist</span>(.x), <span class="st">&quot;}&quot;</span>), <span class="dt">collapse =</span> <span class="st">&quot;, &quot;</span>), <span class="st">&quot;&gt;&quot;</span>))</span></code></pre></div>
<pre><code>## [1] &quot;&lt;{1}, {2}&gt;&quot; &quot;&lt;{1}, {3}&gt;&quot; &quot;&lt;{1}, {4}&gt;&quot; &quot;&lt;{1}, {5}&gt;&quot;</code></pre>
<p>이외에도 AprioriSome 알고리즘, DynamicSome 알고리즘 등의 시퀀스 탐사 알고리즘 들이 존재한다. 보다 자세한 내용은 <span class="citation">전치혁 (<a href="#ref-jun2012datamining" role="doc-biblioref">2012</a>)</span> 및 <span class="citation">Agrawal, Srikant, and others (<a href="#ref-agrawal1995mining" role="doc-biblioref">1995</a>)</span> 참고.</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-agrawal1993mining">
<p>Agrawal, Rakesh, Tomasz Imieliński, and Arun Swami. 1993. “Mining Association Rules Between Sets of Items in Large Databases.” In <em>Proceedings of the 1993 Acm Sigmod International Conference on Management of Data</em>, 207–16. SIGMOD ’93. New York, NY, USA: ACM. <a href="https://doi.org/10.1145/170035.170072">https://doi.org/10.1145/170035.170072</a>.</p>
</div>
<div id="ref-agrawal1994fast">
<p>Agrawal, Rakesh, Ramakrishnan Srikant, and others. 1994. “Fast Algorithms for Mining Association Rules.” In <em>Proc. 20th Int. Conf. Very Large Data Bases, Vldb</em>, 1215:487–99.</p>
</div>
<div id="ref-agrawal1995mining">
<p>Agrawal, Rakesh, Ramakrishnan Srikant, and others. 1995. “Mining Sequential Patterns.” In <em>Icde</em>, 95:3–14.</p>
</div>
<div id="ref-jun2012datamining">
<p>전치혁. 2012. <em>데이터마이닝 기법과 응용</em>. 한나래출판사.</p>
</div>
</div>
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://r-data-mining-book.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
            </section>

          </div>
        </div>
      </div>
<a href="cluster-solution-evaluation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="recommender-system.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["data-mining-book.pdf"],
"toc": {
"collapse": "subsection"
},
"search": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
